# Bootstrap

In [1]:
# show → code input visible by default
# hide-output → output hidden by default
# show hide-output → both (can combine on one line)

# Standard data analysis stack + project utilities
import pandas as pd
from common_lib.sql import BigQueryConnector
from common_lib.export import export_notebook_html
import plotly.express as px
import numpy as np

## Get data

In [2]:
# Toggle to True to re-run the BQ query and overwrite the local cache
refresh_data = True

### Bootstrap

In [3]:
# Point to the SQL file and set the start date for the cohort window
query_location = './sql/bootstrap.sql'
parameters = {
    'start_date': '2026-06-15',
}

bqc = BigQueryConnector()
# Print cost estimate before running — avoids accidental expensive queries (~$1.63 / 242 GB)
cost_info = bqc.print_cost_estimate(query=query_location, is_path=True, query_parameters=parameters)

This query will process 14.96 GB when run.
Estimated query cost: $0.10

In [4]:
data_bootstrap = pd.DataFrame()

if refresh_data:
    data_bootstrap = bqc.get(query='./sql/bootstrap.sql', is_path=True, query_parameters=parameters)
    data_bootstrap.to_pickle('./data/bootstrap.pkl')
else:
    # Load from local cache to avoid repeated query costs
    data_bootstrap = pd.read_pickle('./data/bootstrap.pkl')

In [5]:
data_bootstrap

,timestamp,timestamp_date,server_timestamp,session_id,payload_timestamp,payload_date,user_id,platform,country_code,tutorial_step_id,context,seconds,is_first_session,sequence
0,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.673707Z,2026-06-15,10003F6FA8F5957E,IOS,US,app_launch,cmpt,0.628,False,1
1,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.674769Z,2026-06-15,10003F6FA8F5957E,IOS,US,display_loading_screen,strt,0.656,False,2
2,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.675878Z,2026-06-15,10003F6FA8F5957E,IOS,US,service_manager_process,strt,0.669,False,3
3,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.676762Z,2026-06-15,10003F6FA8F5957E,IOS,US,service_manager_process,cmpt,1.023,False,4
4,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.67766Z,2026-06-15,10003F6FA8F5957E,IOS,US,auth_process,strt,1.034,False,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109550567,2026-07-12 22:08:24.063790+00:00,2026-07-12,None,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:22.40124Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,service_manager_process,cmpt,1.787,False,4
109550568,2026-07-12 22:08:24.063790+00:00,2026-07-12,None,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:22.409203Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,auth_process,strt,1.878,False,5
109550569,2026-07-12 22:08:24.063790+00:00,2026-07-12,2026-07-12T22:08:22.346602Z,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:23.277173Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,auth_process,cmpt,3.492,False,6
109550570,2026-07-12 22:08:26.087755+00:00,2026-07-12,2026-07-12T22:08:22.372466Z,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:23.338848Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,helpshift_sdk,strt,3.553,False,7
109550571,2026-07-12 22:08:26.087755+00:00,2026-07-12,2026-07-12T22:08:22.389352Z,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:23.355729Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,helpshift_sdk,cmpt,3.569,False,8

In [6]:
data_bootstrap.context.unique()

array(['cmpt', 'strt'], dtype=object)

### Session

In [7]:
# Point to the SQL file and set the start date for the cohort window
query_location = './sql/session.sql'
parameters = {
    'start_date': '2026-05-01',
}

bqc = BigQueryConnector()
# Print cost estimate before running — avoids accidental expensive queries (~$1.63 / 242 GB)
cost_info = bqc.print_cost_estimate(query=query_location, is_path=True, query_parameters=parameters)

This query will process 2.78 GB when run.
Estimated query cost: $0.02

In [8]:
data_session = pd.DataFrame()

if refresh_data:
    data_session = pd.DataFrame()
    data_session = bqc.get(query='./sql/session.sql', is_path=True, query_parameters=parameters)
    data_session.to_pickle('./data/session.pkl')
else:
    # Load from local cache to avoid repeated query costs
    data_session = pd.read_pickle('./data/session.pkl')

In [9]:
data_session

,dt,platform,user_id,build_version,count_distinct_users,count_distinct_users_capped,sum_sessions_active,sum_minutes_played,sum_minutes_played_capped
0,2026-05-01,AND,5AF06A188930F6B8,0.74.0,1,0,2,33,33
1,2026-05-01,IOS,30108F538EE4FD1,0.73.0,1,0,2,2,2
2,2026-05-01,IOS,F528168C0C3EB0AF,0.73.0,1,0,2,6,6
3,2026-05-01,AND,9A2E639E810EC838,0.74.0,1,0,10,62,62
4,2026-05-01,IOS,5868CE74187771B2,0.74.0,1,0,6,35,35
...,...,...,...,...,...,...,...,...,...
6901577,2026-07-26,AND,FFA2E9E557EDCFE3,0.80.0,1,0,3,10,10
6901578,2026-07-26,IOS,4DA67C1F2F693446,0.80.0,1,0,2,32,32
6901579,2026-07-26,AND,BE0F1E327564CEDD,0.80.0,1,0,2,34,34
6901580,2026-07-26,AND,D7EE7D65F472E92A,0.80.0,1,0,1,3,3
6901581,2026-07-26,IOS,EC35F12B1F1873AD,0.80.0,1,0,8,86,86

### LoadTime

In [10]:
# Point to the SQL file and set the start date for the cohort window
query_location = './sql/loadtime.sql'
parameters = {
    'start_date': '2026-05-01',
}

bqc = BigQueryConnector()
# Print cost estimate before running — avoids accidental expensive queries (~$1.63 / 242 GB)
cost_info = bqc.print_cost_estimate(query=query_location, is_path=True, query_parameters=parameters)

This query will process 8.79 GB when run.
Estimated query cost: $0.06

In [11]:
data_loadtime = pd.DataFrame()

refresh_data = True

if refresh_data:
    data_loadtime = pd.DataFrame()
    data_loadtime = bqc.get(query='./sql/loadtime.sql', is_path=True, query_parameters=parameters)
    data_loadtime.to_pickle('./data/loadtime.pkl')
else:
    # Load from local cache to avoid repeated query costs
    data_loadtime = pd.read_pickle('./data/loadtime.pkl')

In [12]:
data_loadtime

,timestamp_date,build_version,session_id,user_id,platform,country_code,context,seconds
0,2026-07-03,0.78.0,5acb10ea-9b18-4274-a2c0-2321007db943,6E59FD398D328EE0,AND,DE,start,2.206
1,2026-07-03,0.78.0,676c5a87-8d81-4b20-ba9b-7ce4a9394d14,2235899C6B696CB2,IOS,IT,start,1.584
2,2026-05-26,0.75.0,0bc38329-65cd-4e0b-9538-003100035fc6,A500A3865F779C60,IOS,AT,core,0.154
3,2026-05-26,0.75.0,ae58e69c-2084-4add-a9f2-f9431a892f82,E929B320DF3E1DA8,IOS,US,core,0.216
4,2026-05-26,0.75.0,acff99db-d82f-4978-9af8-2e598c7b8cc4,FF9599A197D93C9E,AND,FR,core,0.141
...,...,...,...,...,...,...,...,...
82811274,2026-06-17,0.77.0,bc5858af-0cf7-4fdd-8165-fed54ff85a39,10596AEFC2AA6BAB,IOS,VC,start,1.484
82811275,2026-06-17,0.76.0,394e07eb-2f4d-451b-9eae-a47cf740add7,76CB3FCCDFA34FF7,AND,US,start,1.985
82811276,2026-06-17,0.63.2,25063e88-8f00-4c89-ba58-5163f1b6d02d,B5331E1B95128C62,IOS,SA,start,1.423
82811277,2026-06-17,0.77.0,39b7321d-b424-4720-ba59-cc79f7dc3900,5A7EE53E2497A1D9,AND,BE,start,2.365
82811278,2026-06-17,0.77.0,f3dae0a1-bb5f-4a5c-a620-0501d7989286,9DCE8A17D76E361D,AND,CL,start,3.872

# Bootstrap event analysis

_Section in progress._ This section will identify the earliest in-game milestone that best predicts long-term retention — the "bootstrap moment" — by comparing event completion rates between retained and churned players.

## Start Bootstrap

In [13]:
data_bootstrap_strt = data_bootstrap.loc[data_bootstrap.context == 'strt']

data_bootstrap_strt['main_date'] = data_bootstrap_strt['timestamp_date'].copy()

data_bootstrap_strt

/var/folders/vj/nwmxdwwn0hl5rtj_xcywvvpc0000gn/T/ipykernel_22342/1727746479.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bootstrap_strt['main_date'] = data_bootstrap_strt['timestamp_date'].copy()

,timestamp,timestamp_date,server_timestamp,session_id,payload_timestamp,payload_date,user_id,platform,country_code,tutorial_step_id,context,seconds,is_first_session,sequence,main_date
1,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.674769Z,2026-06-15,10003F6FA8F5957E,IOS,US,display_loading_screen,strt,0.656,False,2,2026-06-15
2,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.675878Z,2026-06-15,10003F6FA8F5957E,IOS,US,service_manager_process,strt,0.669,False,3,2026-06-15
4,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.67766Z,2026-06-15,10003F6FA8F5957E,IOS,US,auth_process,strt,1.034,False,5,2026-06-15
6,2026-06-15 06:40:44.710431+00:00,2026-06-15,2026-06-15T06:40:44.127365Z,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:44.46076Z,2026-06-15,10003F6FA8F5957E,IOS,US,helpshift_sdk,strt,2.856,False,7,2026-06-15
10,2026-06-15 16:15:29.931373+00:00,2026-06-15,None,b13d8860-b3af-4a64-9f6d-4ebe2d27434b,2026-06-15T16:15:27.906394Z,2026-06-15,10003F6FA8F5957E,IOS,US,display_loading_screen,strt,0.333,False,2,2026-06-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109550562,2026-06-27 22:03:47.314906+00:00,2026-06-27,2026-06-27T22:03:45.397967Z,b30c13ae-867d-4ae9-a71e-559f626546eb,2026-06-27T22:03:46.117511Z,2026-06-27,FFFF50B5AB55EE0,AND,GB,helpshift_sdk,strt,3.022,False,7,2026-06-27
109550565,2026-07-12 22:08:24.063790+00:00,2026-07-12,None,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:22.385405Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,display_loading_screen,strt,0.611,False,2,2026-07-12
109550566,2026-07-12 22:08:24.063790+00:00,2026-07-12,None,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:22.392917Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,service_manager_process,strt,0.691,False,3,2026-07-12
109550568,2026-07-12 22:08:24.063790+00:00,2026-07-12,None,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:22.409203Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,auth_process,strt,1.878,False,5,2026-07-12
109550570,2026-07-12 22:08:26.087755+00:00,2026-07-12,2026-07-12T22:08:22.372466Z,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:23.338848Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,helpshift_sdk,strt,3.553,False,7,2026-07-12

### Aggregate start bootstrap

In [14]:
min_users_threshold = 0

data_bootstrap_agg_strt = data_bootstrap_strt.groupby(['main_date', 'platform','tutorial_step_id']).agg(
    unique_users = ('user_id', 'nunique'),
    avg_seconds = ('seconds', 'mean'),
    sessions = ('session_id', 'nunique'),
    records = ('user_id', 'count')
).reset_index()

# add columns to have a min-max normalized version of the avg_seconds, sessions_per_user and records_per_user columns
data_bootstrap_agg_strt['avg_seconds_norm'] = data_bootstrap_agg_strt.groupby('tutorial_step_id')['avg_seconds'].transform(lambda x: (x - x.min()) / (x.max() - x.min()))
data_bootstrap_agg_strt['sessions_per_user'] = data_bootstrap_agg_strt['sessions'] / data_bootstrap_agg_strt['unique_users']
data_bootstrap_agg_strt['sessions_per_user_norm'] = data_bootstrap_agg_strt.groupby('tutorial_step_id')['sessions_per_user'].transform(lambda x: (x - x.min()) / (x.max() - x.min()))
data_bootstrap_agg_strt['records_per_user'] = data_bootstrap_agg_strt['records'] / data_bootstrap_agg_strt['unique_users']
data_bootstrap_agg_strt['records_per_user_norm'] = data_bootstrap_agg_strt.groupby('tutorial_step_id')['records_per_user'].transform(lambda x: (x - x.min()) / (x.max() - x.min()))
data_bootstrap_agg_strt = data_bootstrap_agg_strt[data_bootstrap_agg_strt.unique_users > min_users_threshold]

In [15]:
data_bootstrap_agg_strt.tutorial_step_id.unique()

array(['auth_process', 'display_applovin_consent',
       'display_assets_download_popup', 'display_loading_screen',
       'display_terms_of_service', 'external_notifications_popup',
       'helpshift_sdk', 'service_manager_process', 'update_app_popup',
       'external_do_not_track_popup'], dtype=object)

In [16]:
data_bootstrap_applaunch_strt = data_bootstrap_agg_strt[data_bootstrap_agg_strt['tutorial_step_id'] == 'display_loading_screen']

fig = px.line(data_bootstrap_applaunch_strt, 
              x='main_date', 
              y='sessions_per_user',
              color='platform',
              title='Sessions per user on app_launch step per platform',
              width=800,
              height=400,
              hover_data={'main_date': True, 'unique_users':True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

fig = px.line(data_bootstrap_applaunch_strt, 
              x='main_date', 
              y='avg_seconds',
              color='platform',
              title='Avg duration seconds for app_launch per user per platform',
              width=800,
              height=400,
              hover_data={'main_date': True, 'unique_users':True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

## Complete Bootstrap

In [17]:
# Back and fort on using timestamp or payload_timestamp. Timestamp seems to be the same for some events, payload varies slightly. That is better for ordering the events and since there is little to none different between we will use payload_timestamp for now.
# switch dates to avoid changing all the notebook
data_bootstrap_cmpt = data_bootstrap.loc[data_bootstrap.context == 'cmpt']

data_bootstrap_cmpt['main_date'] = data_bootstrap_cmpt['timestamp_date'].copy()

#data_bootstrap['main_date']=data_bootstrap['timestamp_date']

data_bootstrap_cmpt = data_bootstrap_cmpt[(data_bootstrap_cmpt.context == 'cmpt')&(data_bootstrap_cmpt.main_date < pd.to_datetime('today'))]
data_bootstrap_cmpt.loc[data_bootstrap_cmpt.seconds > 600, 'seconds'] = 601

data_bootstrap_cmpt = data_bootstrap_cmpt[data_bootstrap_cmpt['main_date'] >= pd.to_datetime('2026-04-03')]

data_bootstrap_cmpt

/var/folders/vj/nwmxdwwn0hl5rtj_xcywvvpc0000gn/T/ipykernel_22342/793224963.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bootstrap_cmpt['main_date'] = data_bootstrap_cmpt['timestamp_date'].copy()

,timestamp,timestamp_date,server_timestamp,session_id,payload_timestamp,payload_date,user_id,platform,country_code,tutorial_step_id,context,seconds,is_first_session,sequence,main_date
0,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.673707Z,2026-06-15,10003F6FA8F5957E,IOS,US,app_launch,cmpt,0.628,False,1,2026-06-15
3,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.676762Z,2026-06-15,10003F6FA8F5957E,IOS,US,service_manager_process,cmpt,1.023,False,4,2026-06-15
5,2026-06-15 06:40:44.710431+00:00,2026-06-15,2026-06-15T06:40:44.124722Z,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:44.458101Z,2026-06-15,10003F6FA8F5957E,IOS,US,auth_process,cmpt,2.853,False,6,2026-06-15
7,2026-06-15 06:40:46.932465+00:00,2026-06-15,2026-06-15T06:40:44.129212Z,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:44.462608Z,2026-06-15,10003F6FA8F5957E,IOS,US,helpshift_sdk,cmpt,2.858,False,8,2026-06-15
8,2026-06-15 06:40:54.027718+00:00,2026-06-15,2026-06-15T06:40:52.567203Z,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:52.690032Z,2026-06-15,10003F6FA8F5957E,IOS,US,display_loading_screen,cmpt,11.075,False,9,2026-06-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109550563,2026-06-27 22:03:49.335350+00:00,2026-06-27,2026-06-27T22:03:45.416837Z,b30c13ae-867d-4ae9-a71e-559f626546eb,2026-06-27T22:03:46.136275Z,2026-06-27,FFFF50B5AB55EE0,AND,GB,helpshift_sdk,cmpt,3.040,False,8,2026-06-27
109550564,2026-07-12 22:08:24.063790+00:00,2026-07-12,None,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:22.376042Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,app_launch,cmpt,0.458,False,1,2026-07-12
109550567,2026-07-12 22:08:24.063790+00:00,2026-07-12,None,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:22.40124Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,service_manager_process,cmpt,1.787,False,4,2026-07-12
109550569,2026-07-12 22:08:24.063790+00:00,2026-07-12,2026-07-12T22:08:22.346602Z,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:23.277173Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,auth_process,cmpt,3.492,False,6,2026-07-12
109550571,2026-07-12 22:08:26.087755+00:00,2026-07-12,2026-07-12T22:08:22.389352Z,56106c33-6ab4-4c75-8cf5-74ce6401a03e,2026-07-12T22:08:23.355729Z,2026-07-12,FFFF50B5AB55EE0,AND,GB,helpshift_sdk,cmpt,3.569,False,8,2026-07-12

In [18]:


# calculate global percentiles to remove high value outliers 
percentiles = data_bootstrap_cmpt.groupby(['tutorial_step_id'])['seconds'].quantile([0.1, 0.5, 0.9]).unstack()
percentiles.columns = ['P10', 'P50', 'P90']
percentiles.reset_index(inplace=True)

# set tutorial_step_id order with a tuple of the tutorial_step_id in the desired order
tutorial_step_order = {'01':'app_launch', '02':'display_loading_screen', '03':'external_notifications_popup', '04':'display_applovin_consent', '05':'external_do_not_track_popup', '06':'display_terms_of_service', '07':'auth_process', '08':'helpshift_sdk', '09':'update_app_popup', '10':'service_manager_process', '11':'display_assets_download_popup'}
tutorial_step_order

# join step order to data_bootstrap_cmpt
data_bootstrap_cmpt = data_bootstrap_cmpt.merge(pd.DataFrame(list(tutorial_step_order.items()), columns=['step_order', 'tutorial_step_id']), on='tutorial_step_id', how='left')

# create a non-outliers version of the data by filtering out rows where seconds is greater than the P90 for that tutorial_step_id
data_bootstrap_no_outliers_cmpt = data_bootstrap_cmpt.merge(percentiles[['tutorial_step_id', 'P90']], on='tutorial_step_id', how='left')
data_bootstrap_no_outliers_cmpt = data_bootstrap_no_outliers_cmpt[data_bootstrap_no_outliers_cmpt['seconds'] < data_bootstrap_no_outliers_cmpt['P90']]

# calculate the percentiles P90, P50 and P10 for the seconds metric by main_date and tutorial_step_id
percentiles_by_day = data_bootstrap_cmpt.groupby(['main_date', 'tutorial_step_id'])['seconds'].quantile([0.1, 0.5, 0.9]).unstack()
percentiles_by_day.columns = ['P10', 'P50', 'P90']
percentiles_by_day.reset_index(inplace=True)

percentiles_by_day_melted = percentiles_by_day.melt(id_vars=['main_date', 'tutorial_step_id'], var_name='percentile', value_name='seconds').sort_values(['main_date', 'tutorial_step_id', 'percentile']).reset_index(drop=True)
percentiles

                 tutorial_step_id      P10      P50       P90
0                      app_launch   0.2060   0.2890    0.5950
1                    auth_process   1.3410   2.0220    4.5590
2        display_applovin_consent   3.6830   7.2630   23.2989
3   display_assets_download_popup  13.8790  39.0565  188.9792
4          display_loading_screen   9.0920  16.0600   84.0670
5        display_terms_of_service   7.6952  12.2760   32.7914
6     external_do_not_track_popup  13.8625  25.7595   74.8160
7    external_notifications_popup  12.1770  23.6905   83.2057
8                   helpshift_sdk   1.3510   2.0590    4.6630
9         service_manager_process   0.4930   0.7610    1.8680
10               update_app_popup   4.5870  10.2780   89.0010

In [19]:
# just a check to see if the data makes sense
data_bootstrap_cmpt[data_bootstrap_cmpt['user_id'] == '10003F6FA8F5957E'].sort_values('payload_timestamp')

,timestamp,timestamp_date,server_timestamp,session_id,payload_timestamp,payload_date,user_id,platform,country_code,tutorial_step_id,context,seconds,is_first_session,sequence,main_date,step_order
0,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.673707Z,2026-06-15,10003F6FA8F5957E,IOS,US,app_launch,cmpt,0.628,False,1,2026-06-15,01
1,2026-06-15 06:40:44.710431+00:00,2026-06-15,None,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:42.676762Z,2026-06-15,10003F6FA8F5957E,IOS,US,service_manager_process,cmpt,1.023,False,4,2026-06-15,10
2,2026-06-15 06:40:44.710431+00:00,2026-06-15,2026-06-15T06:40:44.124722Z,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:44.458101Z,2026-06-15,10003F6FA8F5957E,IOS,US,auth_process,cmpt,2.853,False,6,2026-06-15,07
3,2026-06-15 06:40:46.932465+00:00,2026-06-15,2026-06-15T06:40:44.129212Z,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:44.462608Z,2026-06-15,10003F6FA8F5957E,IOS,US,helpshift_sdk,cmpt,2.858,False,8,2026-06-15,08
4,2026-06-15 06:40:54.027718+00:00,2026-06-15,2026-06-15T06:40:52.567203Z,79514e28-a427-4cb9-b924-bd16acc40e78,2026-06-15T06:40:52.690032Z,2026-06-15,10003F6FA8F5957E,IOS,US,display_loading_screen,cmpt,11.075,False,9,2026-06-15,02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,2026-07-25 17:42:50.964049+00:00,2026-07-25,None,21b63d52-a357-4762-b858-493728483514,2026-07-25T17:42:44.591204Z,2026-07-25,10003F6FA8F5957E,IOS,US,app_launch,cmpt,0.300,False,1,2026-07-25,01
259,2026-07-25 17:42:50.964049+00:00,2026-07-25,None,21b63d52-a357-4762-b858-493728483514,2026-07-25T17:42:44.594065Z,2026-07-25,10003F6FA8F5957E,IOS,US,service_manager_process,cmpt,0.701,False,4,2026-07-25,10
260,2026-07-25 17:42:50.964049+00:00,2026-07-25,2026-07-25T17:42:48.082207Z,21b63d52-a357-4762-b858-493728483514,2026-07-25T17:42:49.268544Z,2026-07-25,10003F6FA8F5957E,IOS,US,auth_process,cmpt,5.417,False,6,2026-07-25,07
261,2026-07-25 17:42:52.983581+00:00,2026-07-25,2026-07-25T17:42:48.086223Z,21b63d52-a357-4762-b858-493728483514,2026-07-25T17:42:49.272578Z,2026-07-25,10003F6FA8F5957E,IOS,US,helpshift_sdk,cmpt,5.421,False,8,2026-07-25,08
262,2026-07-25 17:43:05.429679+00:00,2026-07-25,2026-07-25T17:43:02.278626Z,21b63d52-a357-4762-b858-493728483514,2026-07-25T17:43:03.034429Z,2026-07-25,10003F6FA8F5957E,IOS,US,display_loading_screen,cmpt,19.173,False,9,2026-07-25,02

### Aggregate bootstrap

In [20]:
min_users_threshold = 1

data_bootstrap_agg_cmpt = data_bootstrap_cmpt.groupby(['main_date', 'platform','tutorial_step_id']).agg(
    unique_users = ('user_id', 'nunique'),
    avg_seconds = ('seconds', 'mean'),
    sessions = ('session_id', 'nunique'),
    records = ('user_id', 'count')
).reset_index()

# add columns to have a min-max normalized version of the avg_seconds, sessions_per_user and records_per_user columns
data_bootstrap_agg_cmpt['avg_seconds_norm'] = data_bootstrap_agg_cmpt.groupby('tutorial_step_id')['avg_seconds'].transform(lambda x: (x - x.min()) / (x.max() - x.min()))
data_bootstrap_agg_cmpt['sessions_per_user'] = data_bootstrap_agg_cmpt['sessions'] / data_bootstrap_agg_cmpt['unique_users']
data_bootstrap_agg_cmpt['sessions_per_user_norm'] = data_bootstrap_agg_cmpt.groupby('tutorial_step_id')['sessions_per_user'].transform(lambda x: (x - x.min()) / (x.max() - x.min()))
data_bootstrap_agg_cmpt['records_per_user'] = data_bootstrap_agg_cmpt['records'] / data_bootstrap_agg_cmpt['unique_users']
data_bootstrap_agg_cmpt['records_per_user_norm'] = data_bootstrap_agg_cmpt.groupby('tutorial_step_id')['records_per_user'].transform(lambda x: (x - x.min()) / (x.max() - x.min()))
data_bootstrap_agg_cmpt = data_bootstrap_agg_cmpt[data_bootstrap_agg_cmpt.unique_users > min_users_threshold]

In [21]:
pd.to_pickle(data_bootstrap_agg_cmpt, './data/bootstrap_agg.pkl')

In [22]:
data_bootstrap_agg_cmpt

,main_date,platform,tutorial_step_id,unique_users,avg_seconds,sessions,records,avg_seconds_norm,sessions_per_user,sessions_per_user_norm,records_per_user,records_per_user_norm
0,2026-06-15,AND,app_launch,31652,0.553691,110096,110980,0.057441,3.478327,0.191649,3.506256,0.193276
1,2026-06-15,AND,auth_process,31601,5.227015,109677,110215,0.498637,3.470681,0.203657,3.487706,0.195964
2,2026-06-15,AND,display_applovin_consent,503,16.151647,6,510,0.486152,0.011928,0.808151,1.013917,0.138413
3,2026-06-15,AND,display_assets_download_popup,3822,108.678443,3947,3976,0.718584,1.032705,0.164768,1.040293,0.172362
4,2026-06-15,AND,display_loading_screen,30832,90.005415,115529,116286,0.756005,3.747049,0.357093,3.771601,0.354562
...,...,...,...,...,...,...,...,...,...,...,...,...
874,2026-07-26,IOS,external_do_not_track_popup,47,31.710277,47,47,0.026963,1.000000,NaN,1.000000,0.000000
875,2026-07-26,IOS,external_notifications_popup,736,39.657968,737,739,0.126567,1.001359,0.022684,1.004076,0.062609
876,2026-07-26,IOS,helpshift_sdk,42147,5.014864,167359,170545,0.265008,3.970840,0.602840,4.046433,0.566561
877,2026-07-26,IOS,service_manager_process,42270,1.882494,169732,171169,0.400522,4.015425,0.618586,4.049420,0.617983
878,2026-07-26,IOS,update_app_popup,415,42.894856,1351,1477,0.136871,3.255422,0.506227,3.559036,0.498456

### Applaunch step at bootstrap

In [23]:
data_bootstrap_applaunch_cmpt = data_bootstrap_agg_cmpt[data_bootstrap_agg_cmpt['tutorial_step_id'] == 'app_launch']

fig = px.line(data_bootstrap_applaunch_cmpt, 
              x='main_date', 
              y='sessions_per_user',
              color='platform',
              title='Sessions per user on app launch step per platform',
              width=800,
              height=400,
              hover_data={'main_date': True, 'unique_users':True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

fig = px.line(data_bootstrap_applaunch_cmpt, 
              x='main_date', 
              y='avg_seconds',
              color='platform',
              title='Avg duration seconds for app launch step per user per platform',
              width=800,
              height=400,
              hover_data={'main_date': True, 'unique_users':True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

### Start and Complete

In [24]:
fig = px.line(data_bootstrap_applaunch_strt, 
              x='main_date', 
              y='sessions_per_user',
              color='platform',
              title='Sessions per user on display loading screen start step per platform',
              width=800,
              height=400,
              hover_data={'main_date': True, 'unique_users':True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

fig = px.line(data_bootstrap_applaunch_cmpt,
              x='main_date', 
              y='sessions_per_user',
              color='platform',
              title='Sessions per user on display loading screen complete step per platform',
              width=800,
              height=400,
              hover_data={'main_date': True, 'unique_users':True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

### Null sessions at bootstrap

In [25]:
# Calculate null session_id row counts per main_date from data_bootstrap
null_session_id_counts = data_bootstrap_cmpt[data_bootstrap_cmpt['session_id'].isna()].groupby(['main_date', 'platform']).size().reset_index(name='null_session_id_count')
null_session_id_counts

     main_date platform  null_session_id_count
0   2026-06-15      AND                   1761
1   2026-06-15      IOS                   2910
2   2026-06-16      AND                   2135
3   2026-06-16      IOS                   2758
4   2026-06-17      AND                   1735
..         ...      ...                    ...
79  2026-07-24      IOS                   1580
80  2026-07-25      AND                    811
81  2026-07-25      IOS                   1654
82  2026-07-26      AND                   1026
83  2026-07-26      IOS                   1838

[84 rows x 3 columns]

In [26]:
fig = px.line(null_session_id_counts, 
              x='main_date', 
              y='null_session_id_count',
              color='platform',
              title='Null session id counts per platform',
              width=800,
              height=400,
              hover_data={'main_date': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")

fig.show()

## All steps at bootstrap

In [27]:
fig = px.bar(data_bootstrap_agg_cmpt[data_bootstrap_agg_cmpt.platform == 'IOS'], 
              x='main_date', 
              y='sessions_per_user_norm',
              color='tutorial_step_id',
              title='Normalized Average Sessions by Step Type and Main Date',
              facet_col='tutorial_step_id',
              facet_col_wrap=3,
              width=1400,
              height=1200,
              hover_data={'unique_users': True, 'main_date': True, 'tutorial_step_id': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")

fig.show()

In [28]:
fig = px.bar(data_bootstrap_agg_cmpt[data_bootstrap_agg_cmpt.platform == 'AND'], 
              x='main_date', 
              y='sessions_per_user_norm',
              color='tutorial_step_id',
              title='Normalized Average Seconds by Step Type and Main Date',
              facet_col='tutorial_step_id',
              facet_col_wrap=3,
              width=1400,
              height=1200,
              hover_data={'unique_users': True, 'main_date': True, 'tutorial_step_id': True, 'sessions_per_user':True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")

fig.show()

In [29]:
fig = px.bar(data_bootstrap_agg_cmpt, 
              x='main_date', 
              y='avg_seconds',
              color='tutorial_step_id',
              title='Average Seconds by Step Type and Main Date',
              facet_col='platform',
              width=1200,
              height=600,
              hover_data={'unique_users': True, 'avg_seconds': True, 'main_date': True, 'tutorial_step_id': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")

fig.show()

In [30]:
fig = px.line(percentiles_by_day_melted[percentiles_by_day_melted['percentile'] == 'P50'], 
              x='main_date', 
              y='seconds',
              color='tutorial_step_id',
              facet_row='percentile',
              title='Median for step duration by step type and main date',
              width=1200,
              height=600,
              hover_data={'seconds': True, 'main_date': True, 'tutorial_step_id': True},
)
fig.show()

In [31]:
# Filter data for update_app_popup tutorial_step_id
update_app_popup_data = data_bootstrap_cmpt[data_bootstrap_cmpt['tutorial_step_id'] == 'update_app_popup']
display_assets_download_popup_data = data_bootstrap_cmpt[data_bootstrap_cmpt['tutorial_step_id'] == 'display_assets_download_popup']

chart_data = display_assets_download_popup_data

# Set threshold for minimum user representation
min_users_threshold = 1

# Filter update_app_popup_data to remove tutorial_step_ids with fewer than min_users_threshold unique users
chart_data_filtered = chart_data[
    chart_data.groupby('tutorial_step_id')['user_id'].transform('nunique') >= min_users_threshold
]

fig = px.histogram(chart_data_filtered, 
                   x='seconds',
                   nbins=100,
                   title='Distribution of Users by Seconds for x event',
                   labels={'seconds': 'Seconds', 'count': 'Number of Users'},
                   width=1200,
                   height=600,
                   log_x=False,)

# Add percentile lines
percentile_values = percentiles[percentiles['tutorial_step_id'] == 'update_app_popup'].iloc[0]
for percentile in ['P10', 'P50', 'P90']:
    fig.add_vline(x=percentile_values[percentile], 
                  line_dash="dash", 
                  line_color="red",
                  annotation_text=percentile,
                  annotation_position="top")

fig.show()

# Activity sessions

In [32]:
data_session

,dt,platform,user_id,build_version,count_distinct_users,count_distinct_users_capped,sum_sessions_active,sum_minutes_played,sum_minutes_played_capped
0,2026-05-01,AND,5AF06A188930F6B8,0.74.0,1,0,2,33,33
1,2026-05-01,IOS,30108F538EE4FD1,0.73.0,1,0,2,2,2
2,2026-05-01,IOS,F528168C0C3EB0AF,0.73.0,1,0,2,6,6
3,2026-05-01,AND,9A2E639E810EC838,0.74.0,1,0,10,62,62
4,2026-05-01,IOS,5868CE74187771B2,0.74.0,1,0,6,35,35
...,...,...,...,...,...,...,...,...,...
6901577,2026-07-26,AND,FFA2E9E557EDCFE3,0.80.0,1,0,3,10,10
6901578,2026-07-26,IOS,4DA67C1F2F693446,0.80.0,1,0,2,32,32
6901579,2026-07-26,AND,BE0F1E327564CEDD,0.80.0,1,0,2,34,34
6901580,2026-07-26,AND,D7EE7D65F472E92A,0.80.0,1,0,1,3,3
6901581,2026-07-26,IOS,EC35F12B1F1873AD,0.80.0,1,0,8,86,86

## Capped sessions

In [33]:
data_session_capped = data_session[data_session.count_distinct_users_capped.isin([0,1])].groupby(['dt', 'platform']).agg(
    capped_users=('count_distinct_users_capped', 'sum'),
    users =('count_distinct_users', 'sum'),
    sum_minutes_played=('sum_minutes_played', 'sum'),
    median_minutes_played=('sum_minutes_played', 'median'),
    median_minutes_played_capped=('sum_minutes_played_capped', 'median'),
    p90_minutes_played=('sum_minutes_played', lambda x: np.percentile(x, 90)),
    p10_minutes_played=('sum_minutes_played', lambda x: np.percentile(x, 10))
).reset_index()

data_session_capped['avg_minutes_played'] = data_session_capped['sum_minutes_played'] / data_session_capped['users']

data_session_capped

,dt,platform,capped_users,users,sum_minutes_played,median_minutes_played,median_minutes_played_capped,p90_minutes_played,p10_minutes_played,avg_minutes_played
0,2026-05-01,AND,123,35365,2119059,27.0,27.0,95.0,5,59.919666
1,2026-05-01,IOS,210,50089,2094560,23.0,23.0,89.0,4,41.816766
2,2026-05-02,AND,141,35383,2253627,27.0,27.0,95.0,4,63.692366
3,2026-05-02,IOS,261,49612,2271407,23.0,23.0,89.0,4,45.783419
4,2026-05-03,AND,161,36257,1636099,27.0,27.0,96.0,5,45.125052
...,...,...,...,...,...,...,...,...,...,...
169,2026-07-24,IOS,242,42538,1709619,21.0,21.0,85.0,4,40.190394
170,2026-07-25,AND,112,27980,1508764,26.0,26.0,96.0,4,53.922945
171,2026-07-25,IOS,232,41590,1665047,22.0,22.0,89.0,4,40.034792
172,2026-07-26,AND,130,28731,1470950,27.0,27.0,96.0,4,51.197313
173,2026-07-26,IOS,243,42519,2300860,22.0,22.0,90.0,4,54.11369

In [34]:
fig = px.line(data_session_capped,
              x='dt', 
              y='capped_users',
              color='platform',
              title='Capped users per day',
              width=800,
              height=400,
              hover_data={'dt': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()


fig = px.line(data_session_capped,
              x='dt', 
              y='median_minutes_played',
              color='platform',
              title='Median minutes played per day',
              width=800,
              height=400,
              hover_data={'dt': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

fig = px.line(data_session_capped,
              x='dt', 
              y='p90_minutes_played',
              color='platform',
              title='90th percentile minutes played per day',
              width=800,
              height=400,
              hover_data={'dt': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

fig = px.line(data_session_capped,
              x='dt', 
              y='p10_minutes_played',
              color='platform',
              title='10th percentile minutes played per day',
              width=800,
              height=400,
              hover_data={'dt': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

In [35]:
data_session_agg_platform = data_session.groupby(['dt', 'platform']).agg(
    count_distinct_users=('user_id', 'nunique'),
    sum_sessions_active=('sum_sessions_active', 'sum'),
    sum_minutes_played=('sum_minutes_played', 'sum'),
    sum_minutes_played_capped=('sum_minutes_played_capped', 'sum')
).reset_index()

data_session_agg_platform['sessions_per_user'] = data_session_agg_platform['sum_sessions_active'] / data_session_agg_platform['count_distinct_users']
data_session_agg_platform['minutes_played_per_user'] = data_session_agg_platform['sum_minutes_played'] / data_session_agg_platform['count_distinct_users']
data_session_agg_platform['minutes_played_capped_per_user'] = data_session_agg_platform['sum_minutes_played_capped'] / data_session_agg_platform['count_distinct_users']

data_session_agg_platform

,dt,platform,count_distinct_users,sum_sessions_active,sum_minutes_played,sum_minutes_played_capped,sessions_per_user,minutes_played_per_user,minutes_played_capped_per_user
0,2026-05-01,AND,35365,152093,2119059,1474574,4.300664,59.919666,41.695857
1,2026-05-01,IOS,50089,240283,2094560,1929041,4.797121,41.816766,38.512268
2,2026-05-02,AND,35383,151879,2253627,1484887,4.292429,63.692366,41.966114
3,2026-05-02,IOS,49612,233308,2271407,1927439,4.702653,45.783419,38.850258
4,2026-05-03,AND,36257,160995,1636099,1544020,4.440384,45.125052,42.585432
...,...,...,...,...,...,...,...,...,...
169,2026-07-24,IOS,42538,197742,1709619,1560583,4.648597,40.190394,36.686798
170,2026-07-25,AND,27980,117332,1508764,1160081,4.193424,53.922945,41.461079
171,2026-07-25,IOS,41590,189185,1665047,1573365,4.54881,40.034792,37.830368
172,2026-07-26,AND,28731,124851,1470950,1216658,4.345515,51.197313,42.346525
173,2026-07-26,IOS,42519,201454,2300860,1651385,4.737976,54.11369,38.838754

## Per platform

In [36]:
fig = px.line(data_session_agg_platform, 
              x='dt', 
              y='sessions_per_user',
              color='platform',
              title='Sessions per user per build version',
              width=800,
              height=400,
              hover_data={'dt': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

fig = px.line(data_session_agg_platform, 
              x='dt', 
              y='minutes_played_per_user',
              color='platform',
              title='Minutes played per user per build version',
              width=800,
              height=400,
              hover_data={'dt': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

fig = px.line(data_session_agg_platform, 
              x='dt', 
              y='minutes_played_capped_per_user',
              color='platform',
              title='Minutes played per user per build version',
              width=800,
              height=400,
              hover_data={'dt': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

In [37]:
data_session[data_session.build_version == '0.79.0'].sort_values(['dt', 'platform'])

,dt,platform,user_id,build_version,count_distinct_users,count_distinct_users_capped,sum_sessions_active,sum_minutes_played,sum_minutes_played_capped
5576666,2026-07-09,AND,73B59EEFBFCB7382,0.79.0,1,0,18,77,77
5576891,2026-07-09,AND,289DB0480B750D94,0.79.0,1,0,2,73,73
5576900,2026-07-09,AND,D860106F205D8333,0.79.0,1,0,9,30,30
5577304,2026-07-09,AND,2432083DD73D8391,0.79.0,1,0,6,33,33
5577317,2026-07-09,AND,416912D760B0B532,0.79.0,1,0,4,24,24
...,...,...,...,...,...,...,...,...,...
6901486,2026-07-26,IOS,DFC26593262C9B56,0.79.0,1,0,1,2,2
6901530,2026-07-26,IOS,84A9053F49397C6,0.79.0,1,0,1,13,13
6901534,2026-07-26,IOS,6B022C6D3B9A7A40,0.79.0,1,0,2,14,14
6901538,2026-07-26,IOS,703B2F8DFC430325,0.79.0,1,0,1,14,14
6901564,2026-07-26,IOS,1708BB93C774966F,0.79.0,1,0,2,25,25

In [38]:
data_session = data_session[data_session.sum_minutes_played<360]

## Per build version

In [39]:
data_session_agg = data_session.groupby(['dt', 'build_version','platform']).agg(
    avg_sessions_active=('sum_sessions_active', 'mean'),
    avg_minutes_played=('sum_minutes_played', 'mean'),
    unique_users=('user_id', 'nunique')
).reset_index()
data_session_agg

,dt,build_version,platform,avg_sessions_active,avg_minutes_played,unique_users
0,2026-05-01,0.10.2,IOS,2.0,0.0,1
1,2026-05-01,0.10.4,AND,2.0,23.0,2
2,2026-05-01,0.10.4,IOS,1.0,1.5,2
3,2026-05-01,0.12.0,IOS,3.0,54.0,1
4,2026-05-01,0.13.4,AND,1.0,66.0,1
...,...,...,...,...,...,...
11595,2026-07-26,0.8.20,IOS,2.0,64.5,2
11596,2026-07-26,0.80.0,AND,4.656135,44.182891,25004
11597,2026-07-26,0.80.0,IOS,5.01604,39.422345,37718
11598,2026-07-26,unknown,AND,1.837278,11.585799,338
11599,2026-07-26,unknown,IOS,2.441125,21.70826,569

In [40]:
build_versions = ['0.75.0','0.76.0', '0.77.0', '0.78.0', '0.79.0', '0.80.0']
users_threshold = 1000

fig = px.line(data_session_agg[(data_session_agg.build_version.isin(build_versions)) & (data_session_agg.unique_users >= users_threshold)], 
              x='dt', 
              y='avg_sessions_active',
              color='build_version',
              title='Sessions per user per build version',
              facet_col='platform',
              width=1200,
              height=400,
              hover_data={'dt': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-11', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

fig = px.line(data_session_agg[(data_session_agg.build_version.isin(build_versions)) & (data_session_agg.unique_users >= users_threshold)], 
              x='dt', 
              y='avg_minutes_played',
              color='build_version',
              title='Minutes played per user per build version',
              facet_col='platform',
              width=1200,
              height=400,
              hover_data={'dt': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-11', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

# Loadtime

In [41]:
data_loadtime[data_loadtime.user_id == '10003F6FA8F5957E'].sort_values('timestamp_date')

,timestamp_date,build_version,session_id,user_id,platform,country_code,context,seconds
29025568,2026-05-03,0.74.0,2ee90bac-d2c8-4142-bfa7-2ec5e01c376a,10003F6FA8F5957E,IOS,US,start,1.223
77289211,2026-05-03,0.74.0,2ee90bac-d2c8-4142-bfa7-2ec5e01c376a,10003F6FA8F5957E,IOS,US,core,0.319
53207312,2026-05-05,0.74.0,c85b5348-730a-47ea-a558-820571cce050,10003F6FA8F5957E,IOS,US,start,1.261
29063923,2026-05-05,0.74.0,50c58ccc-d01a-475e-a89a-34288d3edcd3,10003F6FA8F5957E,IOS,US,core,0.038
53162924,2026-05-05,0.74.0,da7d17f4-387e-4bc7-aed7-afaeaf1577df,10003F6FA8F5957E,IOS,US,start,1.176
...,...,...,...,...,...,...,...,...
77257566,2026-07-25,0.80.0,21b63d52-a357-4762-b858-493728483514,10003F6FA8F5957E,IOS,US,start,1.265
77289514,2026-07-25,0.80.0,71864e6a-da8b-4d69-96b5-1b46c34e9af9,10003F6FA8F5957E,IOS,US,core,0.115
77239404,2026-07-25,0.80.0,71864e6a-da8b-4d69-96b5-1b46c34e9af9,10003F6FA8F5957E,IOS,US,core,0.204
77176431,2026-07-25,0.80.0,71864e6a-da8b-4d69-96b5-1b46c34e9af9,10003F6FA8F5957E,IOS,US,start,1.370
77156751,2026-07-25,0.80.0,21b63d52-a357-4762-b858-493728483514,10003F6FA8F5957E,IOS,US,core,0.309

In [42]:
data_loadtime_agg = data_loadtime.groupby(['timestamp_date', 'context', 'platform','build_version']).agg(
    users = ('user_id', 'nunique'),
    avg_seconds = ('seconds', 'mean'),
    sessions = ('session_id', 'nunique'),
    records = ('user_id', 'count')
).reset_index() 

data_loadtime_agg['sessions_per_user'] = data_loadtime_agg['sessions'] / data_loadtime_agg['users']

data_loadtime_agg['combined_dimension'] = data_loadtime_agg['platform'] + '_' + data_loadtime_agg['context']

data_loadtime_agg

,timestamp_date,context,platform,build_version,users,avg_seconds,sessions,records,sessions_per_user,combined_dimension
0,2026-05-01,core,AND,0.10.4,2,8.856750,3,4,1.500000,AND_core
1,2026-05-01,core,AND,0.13.4,1,0.210333,1,6,1.000000,AND_core
2,2026-05-01,core,AND,0.16.4,1,0.670333,1,3,1.000000,AND_core
3,2026-05-01,core,AND,0.22.4,1,0.247571,4,7,4.000000,AND_core
4,2026-05-01,core,AND,0.23.8,2,0.386500,6,12,3.000000,AND_core
...,...,...,...,...,...,...,...,...,...,...
25927,2026-07-26,start,IOS,0.78.0,573,1.979633,1272,1279,2.219895,IOS_start
25928,2026-07-26,start,IOS,0.79.0,2061,1.952540,3539,3550,1.717128,IOS_start
25929,2026-07-26,start,IOS,0.8.20,2,2.396000,2,2,1.000000,IOS_start
25930,2026-07-26,start,IOS,0.80.0,37410,2.263035,154012,154635,4.116867,IOS_start
25931,2026-07-26,start,IOS,unknown,544,5.059624,1164,1169,2.139706,IOS_start

In [43]:
context = 'start'

fig = px.line(data_loadtime_agg[(data_loadtime_agg.context == context)& (data_loadtime_agg.build_version.isin(build_versions)) & (data_loadtime_agg.users >= users_threshold)], 
              x='timestamp_date', 
              y='avg_seconds',
              color='build_version',
              title='Average seconds per user per platform and context',
              facet_col='platform',
              width=1200,
              height=600,
              hover_data={'timestamp_date': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

fig = px.line(data_loadtime_agg[(data_loadtime_agg.context == context)& (data_loadtime_agg.build_version.isin(build_versions)) & (data_loadtime_agg.users >= users_threshold)], 
              x='timestamp_date', 
              y='sessions_per_user',
              color='build_version',
              title='Average sessions per user per platform and context',
              facet_col='platform',
              width=1200,
              height=600,
              hover_data={'timestamp_date': True},
)

# draw a vertical line at the date 2026-07-10 to indicate the start of the cohort window
fig.add_vline(x='2026-07-10', line_dash="dash", line_color="red")
# do not attach the y-axis to zero
fig.update_yaxes(rangemode="normal")

fig.show()

Hello, one more update from me on the 
- Overall the engagement recovery continues to show. Both in the main activity events (sessions + time) but also the bootstrap metrics. I believe is just because we are coming into 0.80.0 and players with 0.79.0 issues might have been resolved by now.
- I didn't find any additional proof that less crashing is decreasing our engagement metrics (data measurement culprit). In fact, right now despite the recovery shown, metrics such as capped users remain low. So it is most likely to be discarded. 
- Looked into the LoadTime event, no new clues there, the drop in sessions/time is also visible there, but the behaviour seems consistent with at least the two previous bulid release for start and core context. In the meta context no change at all is detected.

Because of the signals of recovery in engagement I am slowing pivoting to ARPDAU softness analysis
- Our bug witn unlimited bubble ads (introduced mid-April) did push our ad arpdau upwards, with at least no obvious IAP cannibalization (maybe other issues where there. Since we have fixed it the drop in that placement and overall Ad ARPDAU is clear. That is for sure part of our compounding ARPDAU softness reasons.
- Another hypothesis that I want to chase is payers downgrading segments (whether is due to our tests or something else). If you agree that is a hypothesis worth chasing I will spend sometime on this today.