# Main questions

<!-- hide-toc -->
## Key Highlights

- **Prestige adoption:** 8,327 users (5.2%) reached Prestige in Diorama, with a further 1,759 reaching tiers 3–6+, for a total of 10,086 prestige-reached users out of 158,753 participants.
- **Revenue concentration:** Completers are 6.3% of Diorama users but account for 15.4% of IAP revenue once they become completers (~2.4× their user share). This share has grown consistently across all four events (8.4% → 9.1% → 14.7% → 15.4%), with Diorama/Prestige driving more revenue from fewer completers.
- **Retention strength:** Completer D1 return rate was 98.9% and D28 97.1% during their event, with a post-event hangover of only 1%–2% relative drop — broadly consistent across all seasons.
- **Behaviour shift from Prestige:** Diorama completers show no measurable hangover so far, suggesting Prestige is driving earlier completion and shifting revenue earlier into the event. A full post-event comparison is pending.
- **Gem economy:** Completers hold ~3× more gems than the average player (ending balance 1,422 vs 431), with steady, gradual growth with each season of Timed Albums. The completers are the main cause of increased gems ending balances as it is shown by the non-completers metrics and percentile differences.

---

### New — Through the Ages

- **Prestige adoption:** 4,699 users (3.4%) reached Prestige tier 2, with a further 462 reaching tiers 3+, for a total of 5,161 prestige-reached users out of 138,005 participants (3.74%). Adoption is down from Diorama's 6.35%, suggesting either lower carry-over engagement from the previous event or that the Prestige mechanic draws less novelty on its second iteration.
- **Revenue concentration:** 5,679 completers (4.3% of participants) generated 13.0% of IAP revenue during their event (~3.0× their user share). The full IAP share sequence now reads 8.4% → 9.1% → 14.7% → 15.4% → **13.0%** — a step back from Diorama's peak but still well above the first two seasons. In-event ARPU for ThroughTheAges completers was $3.07/DAU, the second highest on record after JoesTastyTravels ($4.04).
- **Retention strength:** ThroughTheAges completers show the strongest in-event retention recorded: D1 99.1%, D7 98.8%, D14 98.8%, D28 98.8%. Post-event hangover data is not yet available as no subsequent event has run after ThroughTheAges.
- **Diorama completer hangover confirmed:** Now that ThroughTheAges has run, Diorama completers show a ~1.2% relative D1 return rate drop (99.0% during Diorama → 97.8% during ThroughTheAges), consistent with the 1–2% hangover pattern seen in all prior cohorts. The earlier "no measurable hangover" note was written with incomplete data; the pattern holds.
- **Gem economy:** ThroughTheAges completers hold an average gem ending balance of ~2,029 (vs ~455 overall average) — a ~4.5× gap, widening from the ~3× reported for Diorama. Completer gem balances continue growing faster than non-completers season over season, reinforcing accumulation among high-engagement players.

<!-- hide-toc -->

### Q1: General numbers on engagement — how many reached Prestige? Was there an increase?

- **8,327 users** reached Prestige (tier 2) in Diorama — **5.2%** of the 158,753 total Diorama participants. 
- A further 1,759 users went deeper into prestige tiers: tier 3 (1,097 · 0.7%), tier 4 (383 · 0.2%), tier 5 (160 · 0.1%), tier 6+ (119).
- For context, completers (proxy for prestigers) grew strongly event over event before Diorama: JoesTastyTravels **2,381** (2.6%) → WinterTales **7,479** (4.1%, +214%) → AppletonLove **12,559** (7.5%, +68%) → Diorama **9,390** (6.3%, −25%).
- The dip in Diorama completers relative to AppletonLove is partly explained by better game balance and partly by the inflated completer count in AppletonLove driven by OrdersV3.

([Completers > Per Event > Users](#Users)) ([Prestigers > Engagement](#Engagement)) 

### Q2: Did we see a revenue uplift for completers? What is the actual % improvement? How do completers perform vs previous timed album instances?

- Completers are **6.3% of Diorama users** but generate **15.4% of IAP revenue** once they become completers (~2.4× their user share) and **5.1% of ad revenue**.
- The IAP contribution of completers has grown consistently across events: 8.4% → 9.1% → 14.7% → **15.4%** — the feature is increasingly self-selecting high-value payers, and Prestige appears to be driving more revenue from fewer completers. NOTE: if we consider completers users total revenue contribution (even before becoming a completer) they can add up to 70% of total IAP contribution, confirming these are mainly payers and have a high incidence on revenue.
- Ad revenue share also grew event over event but appears to have peaked at AppletonLove: 2.0% → 3.1% → 5.2% → **5.1%** (flat vs AppletonLove). NOTE: Ad revenue has spiked afer Diorama for completers. It is worth investigating if this is driven by having seen prestige or something else.

([Completers > Full Event > Revenue](#Revenue)) ([Completers > Daily > Revenue](#Revenue))

### Q3: Hangover for completers — is there one and how does it compare to previous runs?

- The hangover effect exists and is visible in a couple of metrics:
- Return rate D1: the engagement hangover in completers is noticeable, but the drop is very small and, because they are highly engaged players, the return rate remains very healthy. There is no significant difference in hangover between seasons; the relative drop is between 1%–2%.
- ARPU also shows a slight hangover for completers, but the impact has been improving (decreasing) with each season, from −12.91% on Joe's Tasty Travels to −6.24% on AppletonLove.
- Prestige in Diorama has definitely caused a change in completer behaviour, as no hangover is visible so far; instead there appears to be a push for early completion visible in ARPU metrics. This should be interpreted with caution, as Diorama completers have not yet had a full subsequent Timed Album season for a fair comparison.

([Completers > Daily > Hangover > return-rate-engagement](#return-rate-engagement)) ([Completers > Daily > Hangover > arpu](#arpu))


### Q4: Gem inventories — are completers inflating their balances?

- The rising gem inventory is definitely driven by completers. The breakdown by completers/non-completers and the percentile charts show that the average increase is driven by them.

([Economy > Gems > Ending balances](#ending-balances)) ([Ending balances percentiles](#ending-balances-percentiles))

### PENDING — Product categories

- More detailed analysis on what completers/prestigers are spending on

In [1]:
# hide-output
# Imports libraries and initializes the BigQuery connection
import pandas as pd
#from google.cloud import bigquery
from common_lib.sql import BigQueryConnector
from common_lib.export import export_notebook_html
import plotly.graph_objects as go
import plotly.express as px
import numpy as np

<!-- hide --> 
## Aux functions

Helper functions used throughout the notebook. Defines the vertical line events config and the `add_vlines_to_figure` utility for annotating charts with key liveops dates.

In [2]:
# Define vlines configuration
# Defines event timeline markers used for chart annotations
vlines_events = [
    {'x': pd.Timestamp('2025-11-04').timestamp() * 1000, 'annotation_text': 'JoesTastyTravels'},
    {'x': pd.Timestamp('2025-12-16').timestamp() * 1000, 'annotation_text': 'WinterTales'},
    {'x': pd.Timestamp('2026-01-26').timestamp() * 1000, 'annotation_text': 'AppletonLove'},
    {'x': pd.Timestamp('2026-03-08').timestamp() * 1000, 'annotation_text': 'Diorama'},
    {'x': pd.Timestamp('2026-04-18').timestamp() * 1000, 'annotation_text': 'ThroughTheAges'},
    {'x': pd.Timestamp('2026-05-29').timestamp() * 1000, 'annotation_text': 'Appletonians'},
]

def add_vlines_to_figure(fig, vlines_config):
    """
    Add multiple vertical lines to a plotly figure.
    
    Args:
        fig: plotly figure object
        vlines_config: list of dicts with keys 'x', 'annotation_text', and optional 'line_dash', 'line_color', 'line_width'
    """
    for vline in vlines_config:
        fig.add_vline(
            x=vline['x'],
            line_dash=vline.get('line_dash', 'dash'),
            line_color=vline.get('line_color', 'gray'),
            line_width=vline.get('line_width', 1),
            annotation_text=vline['annotation_text'],
            annotation_position='top right'
        )
    return fig

<!-- hide --> 
# Get data

Loads all raw data from BigQuery and caches locally as pickles for fast iteration.

<!-- hide --> 
## activity

Pulls user-level daily activity for each Timed Album event, including sticker packs opened, sets completed, tier reached, and IAP/ad revenue.

In [3]:
# hide-output
# Sets query path and parameters for activity data pull from BigQuery
query_location = './sql/prestige.sql'
parameters = {
    'start_date':'2025-11-01',
}


bqc = BigQueryConnector()
cost_info = bqc.print_cost_estimate(query=query_location, is_path=True, query_parameters=parameters)

This query will process 72.61 GB when run.
Estimated query cost: $0.49

In [5]:
refresh_flag = False
# Loads activity data from BigQuery or reads from cached pickle based on refresh_flag

data = pd.DataFrame()
if refresh_flag:
    data = bqc.get(query='./sql/prestige.sql', is_path=True, query_parameters=parameters)
    data.to_pickle('./data/prestige_data.pkl')
else:
    data = pd.read_pickle('./data/prestige_data.pkl')

In [6]:
# hide-output
# Inspects column names of the activity dataframe
data.columns

Index(['user_id', 'dt', 'max_level', 'liveops_event_definition_id',
       'liveops_iteration_id', 'liveops_iteration_counter',
       'liveops_user_start_dt', 'days_since_event_start', 'active',
       'n_sessions', 'n_stickerpack_opened', 'n_stickerpack_opened_cumu',
       'n_stickers_collected', 'n_stickers_collected_cumu',
       'n_new_stickers_collected', 'n_new_stickers_collected_cumu',
       'n_dupe_stickers_collected', 'n_dupe_stickers_collected_cumu',
       'n_dreamsticker_used', 'n_dreamsticker_used_cumu', 'dupepoints_inflow',
       'dupepoints_inflow_cumu', 'dupepoints_outflow',
       'dupepoints_outflow_cumu', 'dupepoints_balance_start',
       'dupepoints_balance_end', 'n_sets_completed', 'max_tier_reached',
       'loading_timestamp', 'gross_usd_iap_revenue', 'net_usd_iap_revenue',
       'gross_usd_ad_revenue', 'net_usd_ad_revenue', 'user_id_d1',
       'user_id_d3', 'user_id_d7', 'user_id_d14', 'user_id_d28'],
      dtype='object')

<!-- hide --> 
## Economy flows

Pulls gem and economy flow data for deeper inventory and spending analysis.

In [7]:
# hide-output
# Sets query path and parameters for economy flow data pull from BigQuery
query_location = './sql/economyflow.sql'
parameters = {
    'start_date':'2025-11-01',
}


bqc = BigQueryConnector()
cost_info = bqc.print_cost_estimate(query=query_location, is_path=True, query_parameters=parameters)

This query will process 489.44 GB when run.
Estimated query cost: $3.28

In [8]:
refresh_flag = False
# Loads economy flow data from BigQuery or reads from cached pickle based on refresh_flag
data_econ = pd.DataFrame()
if refresh_flag:
    data_econ = bqc.get(query='./sql/economyflow.sql', is_path=True, query_parameters=parameters)
    data_econ.to_pickle('./data/economyflow.pkl')
else:
    data_econ = pd.read_pickle('./data/economyflow.pkl')

In [8]:
# hide-output
# Inspects column names of the economy flow dataframe
data_econ.columns

Index(['dt', 'user_id', 'currency', 'balance_start', 'balance_end',
       'n_economy_inflow', 'n_economy_outflow'],
      dtype='object')

<!-- hide --> 
## Fix some data

Merges the `S5_ThroughTheAges` duplicate into `ThroughTheAges`, fills missing event IDs as `NoTimedAlbum`, and caps `days_since_event_start` at 39.

In [64]:
# hide-output
# Calculates minimum date per event as a reference anchor for relative time

min_dt_per_event = data.groupby('liveops_event_definition_id')['dt'].min().reset_index()
min_dt_per_event.columns = ['liveops_event_definition_id', 'min_dt']
min_dt_per_event

   liveops_event_definition_id      min_dt
0                 NoTimedAlbum  2025-11-01
1      TimedAlbum-AppletonLove  2026-01-25
2      TimedAlbum-Appletonians  2026-05-28
3           TimedAlbum-Diorama  2026-03-07
4  TimedAlbum-JoesTastyTravels  2025-11-03
5    TimedAlbum-ThroughTheAges  2026-04-17
6       TimedAlbum-WinterTales  2025-12-15

In [65]:
# hide-output
# Checks unique liveops_event_definition_id values before data cleaning
data.liveops_event_definition_id.unique()

array(['TimedAlbum-JoesTastyTravels', 'TimedAlbum-WinterTales',
       'TimedAlbum-AppletonLove', 'TimedAlbum-ThroughTheAges',
       'TimedAlbum-Diorama', 'TimedAlbum-Appletonians', 'NoTimedAlbum'],
      dtype=object)

In [66]:
# hide-output
# Merges S5_ThroughTheAges duplicate and fills missing event IDs with 'NoTimedAlbum'
data['liveops_event_definition_id'] = data['liveops_event_definition_id'].replace('TimedAlbum-S5_ThroughTheAges', 'TimedAlbum-ThroughTheAges')
data['liveops_event_definition_id'] = data['liveops_event_definition_id'].fillna('NoTimedAlbum')
data.liveops_event_definition_id.unique()

array(['TimedAlbum-JoesTastyTravels', 'TimedAlbum-WinterTales',
       'TimedAlbum-AppletonLove', 'TimedAlbum-ThroughTheAges',
       'TimedAlbum-Diorama', 'TimedAlbum-Appletonians', 'NoTimedAlbum'],
      dtype=object)

In [67]:
# hide-output
# Caps days_since_event_start at 39 by setting higher values to None
data['days_since_event_start'] = data['days_since_event_start'].apply(lambda x: x if x <= 39 else None)
data['days_since_event_start'].unique()

array([15., 12., 11., 14., 39., 24., 23., 28., 32., 35., 37., 19., 25.,
        7.,  8., 33., 17., 31., 36., 13., 22., 38., 26., nan, 18., 16.,
       30.,  9., 34., 21., 29.,  2.,  4., 27.,  5., 20.,  6., 10.,  3.,
        0.,  1.])

<!-- hide --> 
# Health check and data setup

Creates event-specific dataframes and adds helper columns (`reached_prestige_user_id`, `completer_user_id`, revenue flags) used for all downstream aggregations.

<!-- hide -->
### Daily active users check

Overall daily unique users across all events combined and broken down by event — sanity check on data coverage and event overlap.

In [9]:
# hide-output
# Defines custom event ordering for consistent chart legends throughout the notebook
custom_order = ['NoTimedAlbum', 'TimedAlbum-JoesTastyTravels', 'TimedAlbum-WinterTales', 'TimedAlbum-AppletonLove', 'TimedAlbum-Diorama',  'TimedAlbum-ThroughTheAges', 'TimedAlbum-Appletonians']

In [10]:
# Create a plotly chart showing daily unique users by event
# Aggregates daily unique user counts overall and by event for time-series charting
daily_users = data.groupby(['dt'])['user_id'].nunique().reset_index()
daily_users.columns = ['dt', 'unique_users']

daily_users_event = data.groupby(['dt', 'liveops_event_definition_id'])['user_id'].nunique().reset_index()
daily_users_event.columns = ['dt', 'liveops_event_definition_id', 'unique_users']

In [11]:
# hide-output
# Line chart of overall daily unique users across all events
fig = px.line(daily_users, 
              x='dt', 
              y='unique_users',
              title='Daily Unique Users by Event',
              width=1200,
              height=600,
              hover_data={'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.update_yaxes(rangemode='tozero')
fig.show()

In [12]:
# hide-output
# Line chart of daily unique users broken down by event
fig = px.line(daily_users_event, 
              x='dt', 
              y='unique_users',
              color='liveops_event_definition_id',
              title='Daily Unique Users by Event',
              width=1200,
              height=600,
              hover_data={'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.update_yaxes(rangemode='tozero')
fig.show()

<!-- hide -->
### Define prestigers

In [13]:
# hide-output
# Identifies users who reached Prestige (tier 2) in Diorama
users_reached_prestige_diorama = data[(data['liveops_event_definition_id'] == 'TimedAlbum-Diorama') & (data['max_tier_reached'] == 2)]['user_id'].drop_duplicates()
users_reached_prestige_throughtheages = data[(data['liveops_event_definition_id'] == 'TimedAlbum-ThroughTheAges') & (data['max_tier_reached'] == 2)]['user_id'].drop_duplicates()

data_extended = data.copy()
data_extended = data_extended.merge(
    users_reached_prestige_diorama.to_frame().rename(columns={'user_id': 'reached_prestige_diorama_user_id'}),
    left_on='user_id',
    right_on='reached_prestige_diorama_user_id',
    how='left'
)

data_extended = data_extended.merge(
    users_reached_prestige_throughtheages.to_frame().rename(columns={'user_id': 'reached_prestige_throughtheages_user_id'}),
    left_on='user_id',
    right_on='reached_prestige_throughtheages_user_id',
    how='left'
)

data_extended

,user_id,dt,max_level,liveops_event_definition_id,liveops_iteration_id,liveops_iteration_counter,liveops_user_start_dt,days_since_event_start,active,n_sessions,...,net_usd_iap_revenue,gross_usd_ad_revenue,net_usd_ad_revenue,user_id_d1,user_id_d3,user_id_d7,user_id_d14,user_id_d28,reached_prestige_diorama_user_id,reached_prestige_throughtheages_user_id
0,DAFB418E11A88F1D,2025-11-18,45,TimedAlbum-JoesTastyTravels,202511031000,1,2025-11-08,15,1,2,...,NaN,NaN,NaN,None,None,None,None,DAFB418E11A88F1D,NaN,NaN
1,100437C86119D7A8,2025-12-27,81,TimedAlbum-WinterTales,202512151000,2,2025-12-27,12,1,6,...,NaN,0.011181,0.009504,None,None,100437C86119D7A8,100437C86119D7A8,None,NaN,NaN
2,E0E56FF6D41E7FE0,2025-12-26,47,TimedAlbum-WinterTales,202512151000,1,2025-12-19,11,1,3,...,NaN,NaN,NaN,E0E56FF6D41E7FE0,E0E56FF6D41E7FE0,E0E56FF6D41E7FE0,None,None,NaN,NaN
3,B19D065889B231A8,2025-12-29,16,TimedAlbum-WinterTales,202512151000,1,2025-12-28,14,1,7,...,NaN,0.140872,0.119741,B19D065889B231A8,B19D065889B231A8,B19D065889B231A8,B19D065889B231A8,None,NaN,NaN
4,97028F26A2BB9AB3,2025-12-12,145,TimedAlbum-JoesTastyTravels,202511031000,1,2025-11-05,39,1,4,...,NaN,0.038458,0.032689,None,97028F26A2BB9AB3,None,None,97028F26A2BB9AB3,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24254320,15E13F876800FB7,2026-06-04,19,TimedAlbum-Appletonians,202605281000,2,2026-05-29,7,1,1,...,NaN,NaN,NaN,15E13F876800FB7,15E13F876800FB7,15E13F876800FB7,None,None,NaN,NaN
24254321,55E836DDA4629AED,2026-06-05,150,TimedAlbum-Appletonians,202605281000,5,2026-05-29,8,1,7,...,NaN,0.005581,0.004744,55E836DDA4629AED,55E836DDA4629AED,55E836DDA4629AED,None,None,NaN,NaN
24254322,11F746FD4D98F050,2026-05-29,21,TimedAlbum-Appletonians,202605281000,4,2026-05-29,1,1,1,...,NaN,NaN,NaN,11F746FD4D98F050,None,None,None,None,NaN,NaN
24254323,EC7621093CB71ECD,2026-06-03,151,TimedAlbum-Appletonians,202605281000,6,2026-05-29,6,1,2,...,NaN,NaN,NaN,EC7621093CB71ECD,EC7621093CB71ECD,EC7621093CB71ECD,None,None,NaN,NaN
24254324,A707537BD64E8532,2026-06-04,145,TimedAlbum-Appletonians,202605281000,6,2026-05-29,7,1,2,...,NaN,NaN,NaN,A707537BD64E8532,A707537BD64E8532,A707537BD64E8532,None,None,NaN,NaN

<!-- hide -->
### Extend data  and define completers

In [14]:
# hide-output
# Copies activity data and merges the prestige user flag as a new column



# completers
level_reached_completer = 12
data_extended['completer_user_id'] = data_extended['user_id'].where(data_extended['n_sets_completed'] == level_reached_completer, None)
data_extended['iap_revenue_completers'] = data_extended['gross_usd_iap_revenue'].where(data_extended['n_sets_completed'] == level_reached_completer, 0)
data_extended['ad_revenue_completers'] = data_extended['gross_usd_ad_revenue'].where(data_extended['n_sets_completed'] == level_reached_completer, 0)

users_completer_JoesTastyTravels = data_extended[(data_extended['liveops_event_definition_id'] == 'TimedAlbum-JoesTastyTravels') & (data_extended['n_sets_completed'] == level_reached_completer)].user_id.drop_duplicates()
users_completer_WinterTales = data_extended[(data_extended['liveops_event_definition_id'] == 'TimedAlbum-WinterTales') & (data_extended['n_sets_completed'] == level_reached_completer)].user_id.drop_duplicates()
users_completer_AppletonLove = data_extended[(data_extended['liveops_event_definition_id'] == 'TimedAlbum-AppletonLove') & (data_extended['n_sets_completed'] == level_reached_completer)].user_id.drop_duplicates()
users_completer_Diorama = data_extended[(data_extended['liveops_event_definition_id'] == 'TimedAlbum-Diorama') & (data_extended['n_sets_completed'] == level_reached_completer)].user_id.drop_duplicates()
users_completer_ThroughTheAges = data_extended[(data_extended['liveops_event_definition_id'] == 'TimedAlbum-ThroughTheAges') & (data_extended['n_sets_completed'] == level_reached_completer)].user_id.drop_duplicates()

users_completers_any = pd.concat([
    users_completer_JoesTastyTravels,
    users_completer_WinterTales,
    users_completer_AppletonLove,
    users_completer_Diorama,
    users_completer_ThroughTheAges
]).drop_duplicates()

# near completers
level_reached_near_completer = 10
data_extended['near_completer_user_id'] = data_extended['user_id'].where(data_extended['n_sets_completed'] == level_reached_near_completer, None)
data_extended['iap_revenue_near_completers'] = data_extended['gross_usd_iap_revenue'].where(data_extended['n_sets_completed'] == level_reached_near_completer, 0)
data_extended['ad_revenue_near_completers'] = data_extended['gross_usd_ad_revenue'].where(data_extended['n_sets_completed'] == level_reached_near_completer, 0)

users_near_completer_JoesTastyTravels = data_extended[(data_extended['liveops_event_definition_id'] == 'TimedAlbum-JoesTastyTravels') & (data_extended['n_sets_completed'] == level_reached_near_completer)].user_id.drop_duplicates()
users_near_completer_WinterTales = data_extended[(data_extended['liveops_event_definition_id'] == 'TimedAlbum-WinterTales') & (data_extended['n_sets_completed'] == level_reached_near_completer)].user_id.drop_duplicates()
users_near_completer_AppletonLove = data_extended[(data_extended['liveops_event_definition_id'] == 'TimedAlbum-AppletonLove') & (data_extended['n_sets_completed'] == level_reached_near_completer)].user_id.drop_duplicates()
users_near_completer_Diorama = data_extended[(data_extended['liveops_event_definition_id'] == 'TimedAlbum-Diorama') & (data_extended['n_sets_completed'] == level_reached_near_completer)].user_id.drop_duplicates()
users_near_completer_ThroughTheAges = data_extended[(data_extended['liveops_event_definition_id'] == 'TimedAlbum-ThroughTheAges') & (data_extended['n_sets_completed'] == level_reached_near_completer)].user_id.drop_duplicates()

data_extended

,user_id,dt,max_level,liveops_event_definition_id,liveops_iteration_id,liveops_iteration_counter,liveops_user_start_dt,days_since_event_start,active,n_sessions,...,user_id_d14,user_id_d28,reached_prestige_diorama_user_id,reached_prestige_throughtheages_user_id,completer_user_id,iap_revenue_completers,ad_revenue_completers,near_completer_user_id,iap_revenue_near_completers,ad_revenue_near_completers
0,DAFB418E11A88F1D,2025-11-18,45,TimedAlbum-JoesTastyTravels,202511031000,1,2025-11-08,15,1,2,...,None,DAFB418E11A88F1D,NaN,NaN,None,0.0,0.0,None,0.0,0.0
1,100437C86119D7A8,2025-12-27,81,TimedAlbum-WinterTales,202512151000,2,2025-12-27,12,1,6,...,100437C86119D7A8,None,NaN,NaN,None,0.0,0.0,None,0.0,0.0
2,E0E56FF6D41E7FE0,2025-12-26,47,TimedAlbum-WinterTales,202512151000,1,2025-12-19,11,1,3,...,None,None,NaN,NaN,None,0.0,0.0,None,0.0,0.0
3,B19D065889B231A8,2025-12-29,16,TimedAlbum-WinterTales,202512151000,1,2025-12-28,14,1,7,...,B19D065889B231A8,None,NaN,NaN,None,0.0,0.0,None,0.0,0.0
4,97028F26A2BB9AB3,2025-12-12,145,TimedAlbum-JoesTastyTravels,202511031000,1,2025-11-05,39,1,4,...,None,97028F26A2BB9AB3,NaN,NaN,None,0.0,0.0,None,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24254320,15E13F876800FB7,2026-06-04,19,TimedAlbum-Appletonians,202605281000,2,2026-05-29,7,1,1,...,None,None,NaN,NaN,None,0.0,0.0,None,0.0,0.0
24254321,55E836DDA4629AED,2026-06-05,150,TimedAlbum-Appletonians,202605281000,5,2026-05-29,8,1,7,...,None,None,NaN,NaN,None,0.0,0.0,None,0.0,0.0
24254322,11F746FD4D98F050,2026-05-29,21,TimedAlbum-Appletonians,202605281000,4,2026-05-29,1,1,1,...,None,None,NaN,NaN,None,0.0,0.0,None,0.0,0.0
24254323,EC7621093CB71ECD,2026-06-03,151,TimedAlbum-Appletonians,202605281000,6,2026-05-29,6,1,2,...,None,None,NaN,NaN,None,0.0,0.0,None,0.0,0.0
24254324,A707537BD64E8532,2026-06-04,145,TimedAlbum-Appletonians,202605281000,6,2026-05-29,7,1,2,...,None,None,NaN,NaN,None,0.0,0.0,None,0.0,0.0

In [15]:
# hide-output
# Verifies unique values in the reached_prestige_user_id flag column
data_extended['reached_prestige_diorama_user_id'].unique()
data_extended['reached_prestige_throughtheages_user_id'].unique()

array([nan, '59FEB75F63CC054E', 'D486CA5E4D320056', ...,
       '2165530281F883AF', 'D5C8A1A52FB8B462', '276DB641E07391CF'],
      shape=(4700,), dtype=object)

# Completers

Analysis of users who completed all 12 sets in a Timed Album event — how many there are, what share of total players they represent, and how much revenue they drive.

## Full Event

Aggregate view per event: total completers, completion rate, IAP/ad revenue from completers, and their share of total event revenue.

In [16]:
# hide-output
# Aggregates completer counts, revenue totals, and completion rate per event
data_completers_per_event = data_extended.groupby(['liveops_event_definition_id']).agg(
    unique_users =('user_id', 'nunique'),
    iap_revenue=('gross_usd_iap_revenue', 'sum'),
    ad_revenue=('gross_usd_ad_revenue', 'sum'),
    unique_completers=('completer_user_id', 'nunique'),
    iap_revenue_completers=('iap_revenue_completers', 'sum'),
    ad_revenue_completers=('ad_revenue_completers', 'sum'),
    ).reset_index()

data_completers_per_event['liveops_event_definition_id'] = pd.Categorical(
    data_completers_per_event['liveops_event_definition_id'], 
    categories=custom_order, 
    ordered=True
)
data_completers_per_event = data_completers_per_event.sort_values('liveops_event_definition_id')

data_completers_per_event['pct_change_completers'] = data_completers_per_event['unique_completers'].pct_change()
data_completers_per_event['pct_change_iap_revenue_completers'] = data_completers_per_event['iap_revenue_completers'].pct_change()
data_completers_per_event['pct_change_adrevenue_completers'] = data_completers_per_event['ad_revenue_completers'].pct_change()

data_completers_per_event['percentage_completers'] = data_completers_per_event['unique_completers'] / data_completers_per_event['unique_users']
data_completers_per_event['percentage_iap_revenue_completers'] = data_completers_per_event['iap_revenue_completers'] / data_completers_per_event['iap_revenue']
data_completers_per_event['percentage_ad_revenue_completers'] = data_completers_per_event['ad_revenue_completers'] / data_completers_per_event['ad_revenue']

data_completers_per_event

,liveops_event_definition_id,unique_users,iap_revenue,ad_revenue,unique_completers,iap_revenue_completers,ad_revenue_completers,pct_change_completers,pct_change_iap_revenue_completers,pct_change_adrevenue_completers,percentage_completers,percentage_iap_revenue_completers,percentage_ad_revenue_completers
3,TimedAlbum-JoesTastyTravels,91854,8.745843e+05,229000.364251,2381,73833.232535,4555.938313,NaN,NaN,NaN,0.025922,0.084421,0.019895
5,TimedAlbum-WinterTales,182398,1.598864e+06,445696.113511,7479,144867.002993,13972.668547,2.141117,0.962084,2.066913,0.041004,0.090606,0.031350
0,TimedAlbum-AppletonLove,168225,1.683723e+06,443527.449654,12559,247075.219796,22843.074811,0.679235,0.705531,0.634840,0.074656,0.146743,0.051503
2,TimedAlbum-Diorama,146302,1.405380e+06,409571.072258,9389,216540.096002,20934.926018,-0.252409,-0.123586,-0.083533,0.064175,0.154079,0.051114
4,TimedAlbum-ThroughTheAges,132915,1.341846e+06,390730.682461,5679,209190.720891,17346.100348,-0.395143,-0.033940,-0.171428,0.042727,0.155898,0.044394
1,TimedAlbum-Appletonians,106800,5.626991e+05,167211.825605,20,2863.116601,169.002613,-0.996478,-0.986313,-0.990257,0.000187,0.005088,0.001011

### Users

Bar charts of absolute completer counts and completion rate (completers / total users) per event.

In [17]:
fig = px.bar(data_completers_per_event, 
# Bar chart of absolute completer counts per event
              x='liveops_event_definition_id', 
              y='unique_completers',
              color='liveops_event_definition_id',
              title='Unique Completers by Event',
              width=1200,
              height=600,
              hover_data={'unique_completers': True, 'pct_change_completers': ':.2%'},
              category_orders={'liveops_event_definition_id': custom_order})

fig.show()

fig = px.bar(data_completers_per_event, 
              x='liveops_event_definition_id', 
              y='percentage_completers',
              color='liveops_event_definition_id',
              title='Completion Rate by Event (Completers / Total Users)',
              width=1200,
              height=600,
              hover_data={'percentage_completers': ':.2%', 'unique_completers': True, 'pct_change_completers': ':.2%'},
              category_orders={'liveops_event_definition_id': custom_order})

fig.show()

### Revenue

Bar charts of absolute and percentage IAP and ad revenue contributed by completers, compared across events.

In [18]:
fig = px.bar(data_completers_per_event, 
# Bar chart of absolute IAP revenue from completers per event
              x='liveops_event_definition_id', 
              y='iap_revenue_completers',
              color='liveops_event_definition_id',
              title='Absolute IAP Revenue by completers by Event',
              width=1200,
              height=600,
              hover_data={'iap_revenue_completers': ':.0f', 'unique_completers': True, 'pct_change_iap_revenue_completers': ':.2%'},
              category_orders={'liveops_event_definition_id': custom_order})

fig.show()

fig = px.bar(data_completers_per_event, 
              x='liveops_event_definition_id', 
              y='ad_revenue_completers',
              color='liveops_event_definition_id',
              title='Absolute AD Revenue by completers by Event',
              width=1200,
              height=600,
              hover_data={'ad_revenue_completers': ':.0f', 'unique_completers': True, 'pct_change_adrevenue_completers': ':.2%'},
              category_orders={'liveops_event_definition_id': custom_order})

fig.show()

In [19]:
fig = px.bar(data_completers_per_event, 
# Bar chart of IAP revenue share (%) attributable to completers per event
              x='liveops_event_definition_id', 
              y='percentage_iap_revenue_completers',
              color='liveops_event_definition_id',
              title='% IAP Revenue by completers by Event',
              width=1200,
              height=600,
              hover_data={'percentage_iap_revenue_completers': ':.2%', 'unique_completers': True},
              category_orders={'liveops_event_definition_id': custom_order})

fig.show()

fig = px.bar(data_completers_per_event, 
              x='liveops_event_definition_id', 
              y='percentage_ad_revenue_completers',
              color='liveops_event_definition_id',
              title='% AD Revenue by completers by Event',
              width=1200,
              height=600,
              hover_data={'percentage_ad_revenue_completers': ':.2%', 'unique_completers': True},
              category_orders={'liveops_event_definition_id': custom_order})

fig.show()

## Daily

Time-series breakdowns of completer activity and revenue, both by calendar date and by days since event start.

In [20]:
# hide-output
# Aggregates daily completer user counts and revenue by date and event
data_completers_daily = data_extended.groupby(['dt', 'liveops_event_definition_id']).agg(
    unique_users =('user_id', 'nunique'),
    iap_revenue=('gross_usd_iap_revenue', 'sum'),
    ad_revenue=('gross_usd_ad_revenue', 'sum'),
    unique_completers=('completer_user_id', 'nunique'),
    iap_revenue_completers=('iap_revenue_completers', 'sum'),
    ad_revenue_completers=('ad_revenue_completers', 'sum'),
    unique_usersd1 = ('user_id_d1', 'nunique'),
    unique_usersd7 = ('user_id_d7', 'nunique'),
    unique_usersd14 = ('user_id_d14', 'nunique'),
    unique_usersd28 = ('user_id_d28', 'nunique'),
    ).reset_index()

data_completers_daily['percentage_completers'] = data_completers_daily['unique_completers'] / data_completers_daily['unique_users']

data_completers_daily['return_rate_d1'] = data_completers_daily['unique_usersd1'] / data_completers_daily['unique_users']
data_completers_daily['return_rate_d7'] = data_completers_daily['unique_usersd7'] / data_completers_daily['unique_users']
data_completers_daily['return_rate_d14'] = data_completers_daily['unique_usersd14'] / data_completers_daily['unique_users']
data_completers_daily['return_rate_d28'] = data_completers_daily['unique_usersd28'] / data_completers_daily['unique_users']


data_completers_daily

,dt,liveops_event_definition_id,unique_users,iap_revenue,ad_revenue,unique_completers,iap_revenue_completers,ad_revenue_completers,unique_usersd1,unique_usersd7,unique_usersd14,unique_usersd28,percentage_completers,return_rate_d1,return_rate_d7,return_rate_d14,return_rate_d28
0,2025-11-03,TimedAlbum-JoesTastyTravels,43977,17555.175245,4821.619927,0,0.000000,0.000000,40161,38117,36376,33279,0.000000,0.913227,0.866749,0.827160,0.756736
1,2025-11-04,TimedAlbum-JoesTastyTravels,52210,19458.358318,5546.303387,0,0.000000,0.000000,46118,43678,41699,38082,0.000000,0.883317,0.836583,0.798678,0.729400
2,2025-11-05,TimedAlbum-JoesTastyTravels,52384,19009.259482,5299.839127,0,0.000000,0.000000,46074,43805,41677,37983,0.000000,0.879543,0.836229,0.795606,0.725088
3,2025-11-06,TimedAlbum-JoesTastyTravels,52189,19879.645413,5105.284529,0,0.000000,0.000000,45659,43433,41558,37735,0.000000,0.874878,0.832225,0.796298,0.723045
4,2025-11-07,TimedAlbum-JoesTastyTravels,52011,33367.890619,5084.812072,0,0.000000,0.000000,44855,42873,41169,37378,0.000000,0.862414,0.824306,0.791544,0.718656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,2026-06-12,TimedAlbum-Appletonians,69476,19678.387257,7567.002353,3,116.958805,20.903476,59518,0,0,0,0.000043,0.856670,0.000000,0.000000,0.000000
231,2026-06-13,TimedAlbum-Appletonians,68250,25610.728082,8416.439988,4,337.704221,13.307333,59977,0,0,0,0.000059,0.878784,0.000000,0.000000,0.000000
232,2026-06-14,TimedAlbum-Appletonians,69936,26600.405974,9157.921371,5,81.738002,10.886649,60890,0,0,0,0.000071,0.870653,0.000000,0.000000,0.000000
233,2026-06-15,TimedAlbum-Appletonians,70394,27150.666473,8632.092122,7,301.630000,31.715134,62208,0,0,0,0.000099,0.883712,0.000000,0.000000,0.000000
234,2026-06-16,TimedAlbum-Appletonians,71487,32108.446362,8667.311811,20,1338.132216,56.962886,0,0,0,0,0.000280,0.000000,0.000000,0.000000,0.000000

<!-- hide --> 
### Users

Daily completer user count and completion rate over time (by calendar date and by days since event start), stacked by event.

In [21]:
fig = px.bar(data_completers_daily, 
# Stacked bar chart of daily completer counts by event
              x='dt', 
              y='unique_completers',
              color='liveops_event_definition_id',
              title='Daily Unique Completers by Event',
              width=1200,
              height=600,
              hover_data={'unique_completers': True},
              category_orders={'liveops_event_definition_id': custom_order})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

fig = px.bar(data_completers_daily, 
              x='dt', 
              y='percentage_completers',
              color='liveops_event_definition_id',
              title='Daily Percentage of Unique Completers by Event',
              width=1200,
              height=600,
              hover_data={'unique_completers': True},
              category_orders={'liveops_event_definition_id': custom_order})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [22]:
# hide-output
# Aggregates completers by days since event start for completion-curve analysis
data_completers_dse = data_extended.groupby(['days_since_event_start', 'liveops_event_definition_id']).agg(
    total_users =('user_id', 'nunique'),
    iap_revenue=('gross_usd_iap_revenue', 'sum'),
    ad_revenue=('gross_usd_ad_revenue', 'sum'),
    unique_completers=('completer_user_id', 'nunique'),
    iap_revenue_completers=('iap_revenue_completers', 'mean'),
    ad_revenue_completers=('ad_revenue_completers', 'mean')
    ).reset_index()

data_completers_dse['percentage_completers'] = data_completers_dse['unique_completers'] / data_completers_dse['total_users']

data_completers_dse

,days_since_event_start,liveops_event_definition_id,total_users,iap_revenue,ad_revenue,unique_completers,iap_revenue_completers,ad_revenue_completers,percentage_completers
0,0,TimedAlbum-AppletonLove,87361,32848.389784,10125.143145,0,0.000000,0.000000,0.000000
1,0,TimedAlbum-Appletonians,60477,19862.872574,7568.014581,0,0.000000,0.000000,0.000000
2,0,TimedAlbum-Diorama,73935,44926.431033,9225.661589,0,0.000000,0.000000,0.000000
3,0,TimedAlbum-JoesTastyTravels,43977,17555.175245,4821.619927,0,0.000000,0.000000,0.000000
4,0,TimedAlbum-ThroughTheAges,68239,21532.328273,7550.586252,0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
230,42,TimedAlbum-AppletonLove,89387,39865.141996,10610.822268,11844,0.294785,0.033977,0.132502
231,42,TimedAlbum-Diorama,78186,25816.395883,8685.807518,8979,0.227352,0.029137,0.114842
232,42,TimedAlbum-JoesTastyTravels,50839,17866.627448,5063.017418,2301,0.165956,0.013509,0.045261
233,42,TimedAlbum-ThroughTheAges,70111,61149.608610,7471.712580,5421,0.433253,0.020523,0.077320
234,42,TimedAlbum-WinterTales,97655,25155.847991,9796.132642,7224,0.137269,0.017777,0.073975

In [23]:
fig = px.line(data_completers_dse, 
# Line chart of completion percentage by days since event start per event
              x='days_since_event_start', 
              y='percentage_completers',
              color='liveops_event_definition_id',
              title='Percentage of Unique Completers by Event by Days Since Event Start',
              width=1200,
              height=600,
              hover_data={'unique_completers': True},
              category_orders={'liveops_event_definition_id': custom_order})


fig.show()

### Revenue

Daily IAP and ad revenue from completers over time and by days since event start, per event.

In [24]:
fig = px.bar(data_completers_daily, 
# Stacked bar chart of daily IAP revenue from completers by event
              x='dt', 
              y='iap_revenue_completers',
              color='liveops_event_definition_id',
              title='Daily IAP Revenue by Event for completers',
              width=1200,
              height=600,
              hover_data={'iap_revenue_completers': True, 'unique_completers': True},
              category_orders={'liveops_event_definition_id': custom_order})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

fig = px.bar(data_completers_daily, 
              x='dt', 
              y='ad_revenue_completers',
              color='liveops_event_definition_id',
              title='Daily AD Revenue by Event for completers',
              width=1200,
              height=600,
              hover_data={'ad_revenue_completers': True, 'unique_completers': True},
              category_orders={'liveops_event_definition_id': custom_order})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [25]:
fig = px.line(data_completers_dse, 
# Line chart of IAP revenue from completers by days since event start
              x='days_since_event_start', 
              y='iap_revenue_completers',
              color='liveops_event_definition_id',
              title='Daily IAP Revenue by Event for completers by Days Since Event Start',
              width=1200,
              height=600,
              hover_data={'iap_revenue_completers': True, 'unique_completers': True},
              category_orders={'liveops_event_definition_id': custom_order})

fig.show()

fig = px.line(data_completers_dse, 
              x='days_since_event_start', 
              y='ad_revenue_completers',
              color='liveops_event_definition_id',
              title='Daily AD Revenue by Event for completers by Days Since Event Start',
              width=1200,
              height=600,
              hover_data={'ad_revenue_completers': True, 'unique_completers': True},
              category_orders={'liveops_event_definition_id': custom_order})

fig.show()

## Hangover

Tracks completer cohorts from each event across all subsequent dates — measures ongoing engagement and ARPDAU after the event ends to detect post-event revenue effects.

In [26]:
# hide-output
# Create a loop to iterate through all events and aggregate results
events = custom_order
user_sets = [users_completer_JoesTastyTravels, users_completer_WinterTales, users_completer_AppletonLove, users_completer_Diorama, users_completer_ThroughTheAges]
#user_sets = [users_near_completer_JoesTastyTravels, users_near_completer_WinterTales, users_near_completer_AppletonLove, users_near_completer_Diorama, users_near_completer_ThroughTheAges]
user_set_names = ['JoesTastyTravels', 'WinterTales', 'AppletonLove', 'Diorama', 'ThroughTheAges']
results_completers_list = []
results_non_completers_list = []

for set, set_name in zip(user_sets, user_set_names):
    event_completers_data = data_extended[(data_extended['user_id'].isin(set))]
    
    event_completers_aggregated = event_completers_data.groupby(['dt']).agg(
        unique_users=('user_id', 'nunique'),
        iap_revenue=('gross_usd_iap_revenue', 'sum'),
        ad_revenue=('gross_usd_ad_revenue', 'sum'),
        unique_usersd1 = ('user_id_d1', 'nunique'),
        unique_usersd7 = ('user_id_d7', 'nunique'),
        unique_usersd14 = ('user_id_d14', 'nunique'),
        unique_usersd28 = ('user_id_d28', 'nunique'),
    ).reset_index()
    
    event_completers_aggregated['set_completed'] = set_name

    event_completers_aggregated['return_rate_d1'] = event_completers_aggregated['unique_usersd1'] / event_completers_aggregated['unique_users']
    event_completers_aggregated['return_rate_d7'] = event_completers_aggregated['unique_usersd7'] / event_completers_aggregated['unique_users']
    event_completers_aggregated['return_rate_d14'] = event_completers_aggregated['unique_usersd14'] / event_completers_aggregated['unique_users']
    event_completers_aggregated['return_rate_d28'] = event_completers_aggregated['unique_usersd28'] / event_completers_aggregated['unique_users']

    # if return rates equal zero then value is null
    event_completers_aggregated['return_rate_d1'] = event_completers_aggregated['return_rate_d1'].replace(0, None)
    event_completers_aggregated['return_rate_d7'] = event_completers_aggregated['return_rate_d7'].replace(0, None)
    event_completers_aggregated['return_rate_d14'] = event_completers_aggregated['return_rate_d14'].replace(0, None)
    event_completers_aggregated['return_rate_d28'] = event_completers_aggregated['return_rate_d28'].replace(0, None)

    results_completers_list.append(event_completers_aggregated)

data_completers_all_events = pd.concat(results_completers_list, ignore_index=True)

data_completers_all_events['arpdau_completers'] = data_completers_all_events['iap_revenue'] / data_completers_all_events['unique_users']

filter_mask = ['JoesTastyTravels', 'WinterTales', 'AppletonLove', 'Diorama', 'ThroughTheAges']

data_completers_all_events = data_completers_all_events[data_completers_all_events['set_completed'].isin(filter_mask)]

data_completers_all_events

,dt,unique_users,iap_revenue,ad_revenue,unique_usersd1,unique_usersd7,unique_usersd14,unique_usersd28,set_completed,return_rate_d1,return_rate_d7,return_rate_d14,return_rate_d28,arpdau_completers
0,2025-11-01,2105,7173.314874,626.561418,2067,2070,2073,2065,JoesTastyTravels,0.981948,0.983373,0.984798,0.980998,3.407751
1,2025-11-02,2123,6013.963992,631.410488,2091,2094,2092,2091,JoesTastyTravels,0.984927,0.98634,0.985398,0.984927,2.832767
2,2025-11-03,2140,7773.309696,687.915881,2114,2117,2108,2117,JoesTastyTravels,0.98785,0.989252,0.985047,0.989252,3.632388
3,2025-11-04,2151,8203.785549,654.473851,2130,2130,2119,2135,JoesTastyTravels,0.990237,0.990237,0.985123,0.992562,3.813940
4,2025-11-05,2162,8442.740820,638.434900,2146,2142,2134,2145,JoesTastyTravels,0.992599,0.990749,0.987049,0.992137,3.905061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,2026-06-12,5203,10029.943082,1418.126549,5081,0,0,0,ThroughTheAges,0.976552,None,None,None,1.927723
1136,2026-06-13,5154,12823.724478,1497.705171,5070,0,0,0,ThroughTheAges,0.983702,None,None,None,2.488111
1137,2026-06-14,5174,12906.890274,1697.933595,5091,0,0,0,ThroughTheAges,0.983958,None,None,None,2.494567
1138,2026-06-15,5169,13686.336656,1578.244734,5088,0,0,0,ThroughTheAges,0.98433,None,None,None,2.647773
1139,2026-06-16,5167,17292.166048,1593.894295,0,0,0,0,ThroughTheAges,None,None,None,None,3.346655

In [27]:
# hide-output
# Builds a date-to-days_since_event_start calendar lookup per event

# create a lookup dataframe that contains the all dates in the calendar and their days_from_event_start, removing null ones
calendar_lookup = data_extended[['liveops_event_definition_id','dt', 'days_since_event_start']].dropna().drop_duplicates().sort_values('dt').reset_index(drop=True)

calendar_lookup.rename(columns={'liveops_event_definition_id': 'set_running'}, inplace=True)

# get only the string part after the dash in set_running to match with the 'set_completed' column in data_completers_all_events
calendar_lookup['set_running'] = calendar_lookup['set_running'].apply(lambda x: x.split('-', 1)[1] if '-' in x else x)

# merge calendar_lookup with data_completers_all_events to get the days_since_event_start for each date, keeping all rows in data_completers_all_events
data_completers_all_events = data_completers_all_events.merge(calendar_lookup, on='dt', how='left')

data_completers_all_events[['dt', 'set_completed', 'set_running', 'days_since_event_start']].sort_values('dt')

              dt     set_completed   set_running  days_since_event_start
0     2025-11-01  JoesTastyTravels           NaN                    <NA>
474   2025-11-01      AppletonLove           NaN                    <NA>
711   2025-11-01           Diorama           NaN                    <NA>
237   2025-11-01       WinterTales           NaN                    <NA>
948   2025-11-01    ThroughTheAges           NaN                    <NA>
...          ...               ...           ...                     ...
710   2026-06-16      AppletonLove  Appletonians                      19
473   2026-06-16       WinterTales  Appletonians                      19
236   2026-06-16  JoesTastyTravels  Appletonians                      19
947   2026-06-16           Diorama  Appletonians                      19
1184  2026-06-16    ThroughTheAges  Appletonians                      19

[1185 rows x 4 columns]

In [28]:
# hide-output
# Line chart of daily unique completer users across all events over time
fig = px.line(data_completers_all_events, 
              x='dt', 
              y='unique_users',
              color='set_completed',
              title='Daily Unique Users that were completers of each event',
              width=1200,
              height=600,
              hover_data={'iap_revenue': True, 'unique_users': True},
              category_orders={'set': custom_order})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

#### Return rate (Engagement)

In [29]:
fig = px.line(data_completers_all_events, 
# Line chart of D1 return rate by completer cohort over calendar time
              x='dt', 
              y='return_rate_d1',
              color='set_completed',
              title='Daily Return Rate (D1) by completers of each event',
              width=1200,
              height=600,
              hover_data={'unique_usersd1': True, 'unique_users': True},
              category_orders={'set': custom_order})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [30]:
# hide-output
# Creates a combined set_completed+running column for grouped cohort analysis
data_completers_all_events['set_completed+running'] = data_completers_all_events['set_completed'] + '-' + data_completers_all_events['set_running']
data_completers_all_events

,dt,unique_users,iap_revenue,ad_revenue,unique_usersd1,unique_usersd7,unique_usersd14,unique_usersd28,set_completed,return_rate_d1,return_rate_d7,return_rate_d14,return_rate_d28,arpdau_completers,set_running,days_since_event_start,set_completed+running
0,2025-11-01,2105,7173.314874,626.561418,2067,2070,2073,2065,JoesTastyTravels,0.981948,0.983373,0.984798,0.980998,3.407751,NaN,<NA>,NaN
1,2025-11-02,2123,6013.963992,631.410488,2091,2094,2092,2091,JoesTastyTravels,0.984927,0.98634,0.985398,0.984927,2.832767,NaN,<NA>,NaN
2,2025-11-03,2140,7773.309696,687.915881,2114,2117,2108,2117,JoesTastyTravels,0.98785,0.989252,0.985047,0.989252,3.632388,JoesTastyTravels,0,JoesTastyTravels-JoesTastyTravels
3,2025-11-04,2151,8203.785549,654.473851,2130,2130,2119,2135,JoesTastyTravels,0.990237,0.990237,0.985123,0.992562,3.813940,JoesTastyTravels,1,JoesTastyTravels-JoesTastyTravels
4,2025-11-05,2162,8442.740820,638.434900,2146,2142,2134,2145,JoesTastyTravels,0.992599,0.990749,0.987049,0.992137,3.905061,JoesTastyTravels,2,JoesTastyTravels-JoesTastyTravels
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,2026-06-12,5203,10029.943082,1418.126549,5081,0,0,0,ThroughTheAges,0.976552,None,None,None,1.927723,Appletonians,15,ThroughTheAges-Appletonians
1181,2026-06-13,5154,12823.724478,1497.705171,5070,0,0,0,ThroughTheAges,0.983702,None,None,None,2.488111,Appletonians,16,ThroughTheAges-Appletonians
1182,2026-06-14,5174,12906.890274,1697.933595,5091,0,0,0,ThroughTheAges,0.983958,None,None,None,2.494567,Appletonians,17,ThroughTheAges-Appletonians
1183,2026-06-15,5169,13686.336656,1578.244734,5088,0,0,0,ThroughTheAges,0.98433,None,None,None,2.647773,Appletonians,18,ThroughTheAges-Appletonians
1184,2026-06-16,5167,17292.166048,1593.894295,0,0,0,0,ThroughTheAges,None,None,None,None,3.346655,Appletonians,19,ThroughTheAges-Appletonians

In [31]:
# hide-output
# Aggregates completer engagement metrics across event combinations

order = ['JoesTastyTravels', 'WinterTales', 'AppletonLove', 'Diorama', 'ThroughTheAges']

data_completers_all_events_aggregated = data_completers_all_events.groupby(['set_completed+running','set_completed','set_running']).agg(
    unique_users=('unique_users', 'sum'),
    iap_revenue=('iap_revenue', 'sum'),
    ad_revenue=('ad_revenue', 'sum'),
    return_rate_d1=('return_rate_d1', 'mean'),
    return_rate_d7=('return_rate_d7', 'mean'),
    return_rate_d14=('return_rate_d14', 'mean'),
    return_rate_d28=('return_rate_d28', 'mean')
    ).reset_index()

data_completers_all_events_aggregated['arpdau'] = data_completers_all_events_aggregated['iap_revenue'] / data_completers_all_events_aggregated['unique_users']

# Sort data_completers_all_events_aggregated by custom order
data_completers_all_events_aggregated['set_completed'] = pd.Categorical(
    data_completers_all_events_aggregated['set_completed'],
    categories=order,
    ordered=True
)
data_completers_all_events_aggregated['set_running'] = pd.Categorical(
    data_completers_all_events_aggregated['set_running'],
    categories=order,
    ordered=True
)

data_completers_all_events_aggregated = data_completers_all_events_aggregated.sort_values(
    by=['set_completed', 'set_running']
).reset_index(drop=True)

data_completers_all_events_aggregated

,set_completed+running,set_completed,set_running,unique_users,iap_revenue,ad_revenue,return_rate_d1,return_rate_d7,return_rate_d14,return_rate_d28,arpdau
0,JoesTastyTravels-JoesTastyTravels,JoesTastyTravels,JoesTastyTravels,98078,4.015253e+05,31558.668012,0.98952,0.982602,0.97114,0.938872,4.093938
1,JoesTastyTravels-WinterTales,JoesTastyTravels,WinterTales,90907,3.229032e+05,28359.428952,0.977246,0.950986,0.928065,0.892663,3.552017
2,JoesTastyTravels-AppletonLove,JoesTastyTravels,AppletonLove,80096,2.717684e+05,25387.324227,0.974712,0.951215,0.927628,0.882521,3.393033
3,JoesTastyTravels-Diorama,JoesTastyTravels,Diorama,70063,2.247907e+05,22619.674728,0.970433,0.949239,0.930544,0.90168,3.208408
4,JoesTastyTravels-ThroughTheAges,JoesTastyTravels,ThroughTheAges,63994,2.187906e+05,23117.604985,0.966632,0.945181,0.927018,0.895896,3.418924
5,JoesTastyTravels-Appletonians,JoesTastyTravels,NaN,27735,9.636694e+04,10049.989015,0.964751,0.946245,0.931769,NaN,3.474561
6,WinterTales-JoesTastyTravels,WinterTales,JoesTastyTravels,263963,5.586836e+05,61683.447166,0.984408,0.978942,0.977005,0.978748,2.116522
7,WinterTales-WinterTales,WinterTales,WinterTales,308958,7.854895e+05,81827.946432,0.989229,0.981128,0.972335,0.944097,2.542383
8,WinterTales-AppletonLove,WinterTales,AppletonLove,287991,7.042660e+05,75686.212721,0.980672,0.954291,0.927171,0.877415,2.445445
9,WinterTales-Diorama,WinterTales,Diorama,246558,5.343153e+05,63610.067028,0.974414,0.95182,0.930444,0.895257,2.167098
10,WinterTales-ThroughTheAges,WinterTales,ThroughTheAges,220746,4.914201e+05,61537.282905,0.970662,0.949393,0.931245,0.89965,2.226179
11,WinterTales-Appletonians,WinterTales,NaN,95552,2.084276e+05,26296.816432,0.969211,0.94976,0.933786,NaN,2.181300
12,AppletonLove-JoesTastyTravels,AppletonLove,JoesTastyTravels,393493,5.975576e+05,78942.687742,0.977201,0.968193,0.963393,0.960203,1.518598
13,AppletonLove-WinterTales,AppletonLove,WinterTales,454740,7.800607e+05,101662.995712,0.980862,0.974919,0.975881,0.980988,1.715399
14,AppletonLove-AppletonLove,AppletonLove,AppletonLove,518506,1.090937e+06,132308.249207,0.987688,0.977755,0.963871,0.925148,2.104001
15,AppletonLove-Diorama,AppletonLove,Diorama,470968,8.731801e+05,116147.896034,0.97556,0.948218,0.921715,0.876503,1.854011
16,AppletonLove-ThroughTheAges,AppletonLove,ThroughTheAges,405215,7.403221e+05,102154.804673,0.968799,0.943702,0.922901,0.885179,1.826986
17,AppletonLove-Appletonians,AppletonLove,NaN,172402,3.057296e+05,42362.904264,0.966072,0.945783,0.928342,NaN,1.773353
18,Diorama-JoesTastyTravels,Diorama,JoesTastyTravels,293156,4.703317e+05,61076.001578,0.9793,0.971018,0.966524,0.962818,1.604374
19,Diorama-WinterTales,Diorama,WinterTales,321922,5.799063e+05,73602.639941,0.982558,0.97571,0.974713,0.97641,1.801388
20,Diorama-AppletonLove,Diorama,AppletonLove,358582,7.699048e+05,92606.118842,0.987055,0.983126,0.982179,0.982705,2.147082
21,Diorama-Diorama,Diorama,Diorama,391419,8.982117e+05,111023.823605,0.98918,0.981234,0.970731,0.941513,2.294758
22,Diorama-ThroughTheAges,Diorama,ThroughTheAges,361655,8.073359e+05,104284.300195,0.977135,0.950782,0.926467,0.882442,2.232337
23,Diorama-Appletonians,Diorama,NaN,150348,3.204041e+05,41486.630244,0.972137,0.949381,0.927472,NaN,2.131083
24,ThroughTheAges-JoesTastyTravels,ThroughTheAges,JoesTastyTravels,180907,3.567158e+05,38858.567691,0.982646,0.97493,0.970484,0.965938,1.971819
25,ThroughTheAges-WinterTales,ThroughTheAges,WinterTales,195766,4.265372e+05,46836.929100,0.985445,0.978837,0.977074,0.976971,2.178811
26,ThroughTheAges-AppletonLove,ThroughTheAges,AppletonLove,210177,5.320312e+05,56625.420633,0.987942,0.983078,0.98137,0.979799,2.531348
27,ThroughTheAges-Diorama,ThroughTheAges,Diorama,224889,5.955156e+05,65706.133246,0.989177,0.985722,0.985114,0.986754,2.648042
28,ThroughTheAges-ThroughTheAges,ThroughTheAges,ThroughTheAges,238190,7.684661e+05,82077.616284,0.990221,0.981298,0.970779,0.953436,3.226274
29,ThroughTheAges-Appletonians,ThroughTheAges,NaN,105590,3.246685e+05,34344.193860,0.982288,0.962498,0.943012,NaN,3.074804

In [32]:
# hide-output
# Assigns sequence numbers based on event progression order

# Find the row where set_completed == set_running for each event
data_completers_all_events_aggregated['sequence'] = 0

for event in order:
    event_mask = data_completers_all_events_aggregated['set_completed'] == event
    event_indices = data_completers_all_events_aggregated[event_mask].index.tolist()
    
    # Find the index where set_completed == set_running
    zero_idx = None
    zero_position = None
    for i, idx in enumerate(event_indices):
        if data_completers_all_events_aggregated.loc[idx, 'set_completed'] == data_completers_all_events_aggregated.loc[idx, 'set_running']:
            zero_idx = idx
            zero_position = i
            break
    
    if zero_idx is not None:
        # Assign sequence numbers: negative before zero, positive after
        for i, idx in enumerate(event_indices):
            data_completers_all_events_aggregated.loc[idx, 'sequence'] = i - zero_position

data_completers_all_events_aggregated

,set_completed+running,set_completed,set_running,unique_users,iap_revenue,ad_revenue,return_rate_d1,return_rate_d7,return_rate_d14,return_rate_d28,arpdau,sequence
0,JoesTastyTravels-JoesTastyTravels,JoesTastyTravels,JoesTastyTravels,98078,4.015253e+05,31558.668012,0.98952,0.982602,0.97114,0.938872,4.093938,0
1,JoesTastyTravels-WinterTales,JoesTastyTravels,WinterTales,90907,3.229032e+05,28359.428952,0.977246,0.950986,0.928065,0.892663,3.552017,1
2,JoesTastyTravels-AppletonLove,JoesTastyTravels,AppletonLove,80096,2.717684e+05,25387.324227,0.974712,0.951215,0.927628,0.882521,3.393033,2
3,JoesTastyTravels-Diorama,JoesTastyTravels,Diorama,70063,2.247907e+05,22619.674728,0.970433,0.949239,0.930544,0.90168,3.208408,3
4,JoesTastyTravels-ThroughTheAges,JoesTastyTravels,ThroughTheAges,63994,2.187906e+05,23117.604985,0.966632,0.945181,0.927018,0.895896,3.418924,4
5,JoesTastyTravels-Appletonians,JoesTastyTravels,NaN,27735,9.636694e+04,10049.989015,0.964751,0.946245,0.931769,NaN,3.474561,5
6,WinterTales-JoesTastyTravels,WinterTales,JoesTastyTravels,263963,5.586836e+05,61683.447166,0.984408,0.978942,0.977005,0.978748,2.116522,-1
7,WinterTales-WinterTales,WinterTales,WinterTales,308958,7.854895e+05,81827.946432,0.989229,0.981128,0.972335,0.944097,2.542383,0
8,WinterTales-AppletonLove,WinterTales,AppletonLove,287991,7.042660e+05,75686.212721,0.980672,0.954291,0.927171,0.877415,2.445445,1
9,WinterTales-Diorama,WinterTales,Diorama,246558,5.343153e+05,63610.067028,0.974414,0.95182,0.930444,0.895257,2.167098,2
10,WinterTales-ThroughTheAges,WinterTales,ThroughTheAges,220746,4.914201e+05,61537.282905,0.970662,0.949393,0.931245,0.89965,2.226179,3
11,WinterTales-Appletonians,WinterTales,NaN,95552,2.084276e+05,26296.816432,0.969211,0.94976,0.933786,NaN,2.181300,4
12,AppletonLove-JoesTastyTravels,AppletonLove,JoesTastyTravels,393493,5.975576e+05,78942.687742,0.977201,0.968193,0.963393,0.960203,1.518598,-2
13,AppletonLove-WinterTales,AppletonLove,WinterTales,454740,7.800607e+05,101662.995712,0.980862,0.974919,0.975881,0.980988,1.715399,-1
14,AppletonLove-AppletonLove,AppletonLove,AppletonLove,518506,1.090937e+06,132308.249207,0.987688,0.977755,0.963871,0.925148,2.104001,0
15,AppletonLove-Diorama,AppletonLove,Diorama,470968,8.731801e+05,116147.896034,0.97556,0.948218,0.921715,0.876503,1.854011,1
16,AppletonLove-ThroughTheAges,AppletonLove,ThroughTheAges,405215,7.403221e+05,102154.804673,0.968799,0.943702,0.922901,0.885179,1.826986,2
17,AppletonLove-Appletonians,AppletonLove,NaN,172402,3.057296e+05,42362.904264,0.966072,0.945783,0.928342,NaN,1.773353,3
18,Diorama-JoesTastyTravels,Diorama,JoesTastyTravels,293156,4.703317e+05,61076.001578,0.9793,0.971018,0.966524,0.962818,1.604374,-3
19,Diorama-WinterTales,Diorama,WinterTales,321922,5.799063e+05,73602.639941,0.982558,0.97571,0.974713,0.97641,1.801388,-2
20,Diorama-AppletonLove,Diorama,AppletonLove,358582,7.699048e+05,92606.118842,0.987055,0.983126,0.982179,0.982705,2.147082,-1
21,Diorama-Diorama,Diorama,Diorama,391419,8.982117e+05,111023.823605,0.98918,0.981234,0.970731,0.941513,2.294758,0
22,Diorama-ThroughTheAges,Diorama,ThroughTheAges,361655,8.073359e+05,104284.300195,0.977135,0.950782,0.926467,0.882442,2.232337,1
23,Diorama-Appletonians,Diorama,NaN,150348,3.204041e+05,41486.630244,0.972137,0.949381,0.927472,NaN,2.131083,2
24,ThroughTheAges-JoesTastyTravels,ThroughTheAges,JoesTastyTravels,180907,3.567158e+05,38858.567691,0.982646,0.97493,0.970484,0.965938,1.971819,-4
25,ThroughTheAges-WinterTales,ThroughTheAges,WinterTales,195766,4.265372e+05,46836.929100,0.985445,0.978837,0.977074,0.976971,2.178811,-3
26,ThroughTheAges-AppletonLove,ThroughTheAges,AppletonLove,210177,5.320312e+05,56625.420633,0.987942,0.983078,0.98137,0.979799,2.531348,-2
27,ThroughTheAges-Diorama,ThroughTheAges,Diorama,224889,5.955156e+05,65706.133246,0.989177,0.985722,0.985114,0.986754,2.648042,-1
28,ThroughTheAges-ThroughTheAges,ThroughTheAges,ThroughTheAges,238190,7.684661e+05,82077.616284,0.990221,0.981298,0.970779,0.953436,3.226274,0
29,ThroughTheAges-Appletonians,ThroughTheAges,NaN,105590,3.246685e+05,34344.193860,0.982288,0.962498,0.943012,NaN,3.074804,1

In [33]:
fig = px.line(data_completers_all_events, 
# Line chart of D1 return rate by days since event start per completer cohort
              x='days_since_event_start', 
              y='return_rate_d1',
              color='set_completed+running',
              title='Daily Return Rate (D1) by completers of each event',
              width=1200,
              height=600,
              hover_data={'unique_usersd1': True, 'unique_users': True},
              category_orders={'set': custom_order})

#fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

fig = px.line(data_completers_all_events, 
              x='days_since_event_start', 
              y='return_rate_d7',
              color='set_completed+running',
              title='Daily Return Rate (D7) by completers of each event',
              width=1200,
              height=600,
              hover_data={'unique_usersd7': True, 'unique_users': True},
              category_orders={'set': custom_order})

#fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [34]:
fig = px.box(data_completers_all_events, 
# Box plot of D1 return rate distribution by running event for each completer cohort
              x='set_running', 
              y='return_rate_d1',
              color='set_completed',
              title='Daily Return Rate (D1) by completers of each event',
              width=1200,
              height=600,
              hover_data={'return_rate_d1': True, 'unique_users': True},
              category_orders={'set': order,'set_on_date': order})

#fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [35]:
# Convert return_rate columns from object to numeric
# Converts return_rate to numeric and creates a comparison bar chart across cohorts
data_completers_all_events_aggregated['return_rate_d1'] = pd.to_numeric(data_completers_all_events_aggregated['return_rate_d1'], errors='coerce')

fig = px.bar(data_completers_all_events_aggregated, 
              x='set_running', 
              y='return_rate_d1',
              color='set_completed',
              barmode='group',
              title='D1 Return Rate by Completers of Each Event',
              width=1200,
              height=600,
              hover_data={'return_rate_d1': ':2%'},
              category_orders={'set_completed': order, 'set_running': order},
              text='return_rate_d1')

fig.update_traces(textposition='outside', texttemplate='%{text:.2%}')

# Set y-axis to start from a value close to the minimum instead of zero
min_val = data_completers_all_events_aggregated['return_rate_d1'].min()
max_val = data_completers_all_events_aggregated['return_rate_d1'].max()
y_range = max_val - min_val
padding = y_range * 0.1

fig.update_yaxes(tickformat='.2%', range=[max(0, min_val - padding), max_val + padding])

fig.show()

In [36]:
# hide-output
# Calculates relative return rate difference vs. the completer's own event
# Initialize the column if it doesn't exist
if 'return_rate_d1_relative_diff' not in data_completers_all_events_aggregated.columns:
    data_completers_all_events_aggregated['return_rate_d1_relative_diff'] = np.nan

# Calculate return_rate_d1_relative_diff for all events
for event in order:
    event_data = data_completers_all_events_aggregated[
        data_completers_all_events_aggregated['set_completed'] == event
    ].copy()
    
    
    # Get the baseline value when set_running == set_completed
    baseline = event_data[event_data['set_running'] == event]['return_rate_d1'].values
    
    if len(baseline) > 0:
        # Calculate relative diff for all rows in this event
        event_data['return_rate_d1_relative_diff'] = (event_data['return_rate_d1'] - baseline[0]) / baseline[0]
        
        # Update the main dataframe
        data_completers_all_events_aggregated.loc[
            data_completers_all_events_aggregated['set_completed'] == event,
            'return_rate_d1_relative_diff'
        ] = event_data['return_rate_d1_relative_diff'].values


data_completers_all_events_aggregated

,set_completed+running,set_completed,set_running,unique_users,iap_revenue,ad_revenue,return_rate_d1,return_rate_d7,return_rate_d14,return_rate_d28,arpdau,sequence,return_rate_d1_relative_diff
0,JoesTastyTravels-JoesTastyTravels,JoesTastyTravels,JoesTastyTravels,98078,4.015253e+05,31558.668012,0.989520,0.982602,0.97114,0.938872,4.093938,0,0.000000
1,JoesTastyTravels-WinterTales,JoesTastyTravels,WinterTales,90907,3.229032e+05,28359.428952,0.977246,0.950986,0.928065,0.892663,3.552017,1,-0.012403
2,JoesTastyTravels-AppletonLove,JoesTastyTravels,AppletonLove,80096,2.717684e+05,25387.324227,0.974712,0.951215,0.927628,0.882521,3.393033,2,-0.014965
3,JoesTastyTravels-Diorama,JoesTastyTravels,Diorama,70063,2.247907e+05,22619.674728,0.970433,0.949239,0.930544,0.90168,3.208408,3,-0.019289
4,JoesTastyTravels-ThroughTheAges,JoesTastyTravels,ThroughTheAges,63994,2.187906e+05,23117.604985,0.966632,0.945181,0.927018,0.895896,3.418924,4,-0.023130
5,JoesTastyTravels-Appletonians,JoesTastyTravels,NaN,27735,9.636694e+04,10049.989015,0.964751,0.946245,0.931769,NaN,3.474561,5,-0.025031
6,WinterTales-JoesTastyTravels,WinterTales,JoesTastyTravels,263963,5.586836e+05,61683.447166,0.984408,0.978942,0.977005,0.978748,2.116522,-1,-0.004873
7,WinterTales-WinterTales,WinterTales,WinterTales,308958,7.854895e+05,81827.946432,0.989229,0.981128,0.972335,0.944097,2.542383,0,0.000000
8,WinterTales-AppletonLove,WinterTales,AppletonLove,287991,7.042660e+05,75686.212721,0.980672,0.954291,0.927171,0.877415,2.445445,1,-0.008650
9,WinterTales-Diorama,WinterTales,Diorama,246558,5.343153e+05,63610.067028,0.974414,0.95182,0.930444,0.895257,2.167098,2,-0.014976
10,WinterTales-ThroughTheAges,WinterTales,ThroughTheAges,220746,4.914201e+05,61537.282905,0.970662,0.949393,0.931245,0.89965,2.226179,3,-0.018769
11,WinterTales-Appletonians,WinterTales,NaN,95552,2.084276e+05,26296.816432,0.969211,0.94976,0.933786,NaN,2.181300,4,-0.020236
12,AppletonLove-JoesTastyTravels,AppletonLove,JoesTastyTravels,393493,5.975576e+05,78942.687742,0.977201,0.968193,0.963393,0.960203,1.518598,-2,-0.010618
13,AppletonLove-WinterTales,AppletonLove,WinterTales,454740,7.800607e+05,101662.995712,0.980862,0.974919,0.975881,0.980988,1.715399,-1,-0.006912
14,AppletonLove-AppletonLove,AppletonLove,AppletonLove,518506,1.090937e+06,132308.249207,0.987688,0.977755,0.963871,0.925148,2.104001,0,0.000000
15,AppletonLove-Diorama,AppletonLove,Diorama,470968,8.731801e+05,116147.896034,0.975560,0.948218,0.921715,0.876503,1.854011,1,-0.012280
16,AppletonLove-ThroughTheAges,AppletonLove,ThroughTheAges,405215,7.403221e+05,102154.804673,0.968799,0.943702,0.922901,0.885179,1.826986,2,-0.019125
17,AppletonLove-Appletonians,AppletonLove,NaN,172402,3.057296e+05,42362.904264,0.966072,0.945783,0.928342,NaN,1.773353,3,-0.021886
18,Diorama-JoesTastyTravels,Diorama,JoesTastyTravels,293156,4.703317e+05,61076.001578,0.979300,0.971018,0.966524,0.962818,1.604374,-3,-0.009989
19,Diorama-WinterTales,Diorama,WinterTales,321922,5.799063e+05,73602.639941,0.982558,0.97571,0.974713,0.97641,1.801388,-2,-0.006695
20,Diorama-AppletonLove,Diorama,AppletonLove,358582,7.699048e+05,92606.118842,0.987055,0.983126,0.982179,0.982705,2.147082,-1,-0.002148
21,Diorama-Diorama,Diorama,Diorama,391419,8.982117e+05,111023.823605,0.989180,0.981234,0.970731,0.941513,2.294758,0,0.000000
22,Diorama-ThroughTheAges,Diorama,ThroughTheAges,361655,8.073359e+05,104284.300195,0.977135,0.950782,0.926467,0.882442,2.232337,1,-0.012178
23,Diorama-Appletonians,Diorama,NaN,150348,3.204041e+05,41486.630244,0.972137,0.949381,0.927472,NaN,2.131083,2,-0.017230
24,ThroughTheAges-JoesTastyTravels,ThroughTheAges,JoesTastyTravels,180907,3.567158e+05,38858.567691,0.982646,0.97493,0.970484,0.965938,1.971819,-4,-0.007650
25,ThroughTheAges-WinterTales,ThroughTheAges,WinterTales,195766,4.265372e+05,46836.929100,0.985445,0.978837,0.977074,0.976971,2.178811,-3,-0.004823
26,ThroughTheAges-AppletonLove,ThroughTheAges,AppletonLove,210177,5.320312e+05,56625.420633,0.987942,0.983078,0.98137,0.979799,2.531348,-2,-0.002301
27,ThroughTheAges-Diorama,ThroughTheAges,Diorama,224889,5.955156e+05,65706.133246,0.989177,0.985722,0.985114,0.986754,2.648042,-1,-0.001055
28,ThroughTheAges-ThroughTheAges,ThroughTheAges,ThroughTheAges,238190,7.684661e+05,82077.616284,0.990221,0.981298,0.970779,0.953436,3.226274,0,0.000000
29,ThroughTheAges-Appletonians,ThroughTheAges,NaN,105590,3.246685e+05,34344.193860,0.982288,0.962498,0.943012,NaN,3.074804,1,-0.008011

In [37]:
fig = px.line(data_completers_all_events_aggregated, 
# Line chart of relative return rate difference (%) by running event across cohorts
              x='set_running', 
              y='return_rate_d1_relative_diff',
              color='set_completed',
              title='Relative Difference in Return Rate by Completers of Each Event (%)',
              width=1200,
              height=600,
              hover_data={'return_rate_d1_relative_diff': ':.2%'},
              category_orders={'set_completed': order, 'set_running': order},
              text='return_rate_d1_relative_diff')

fig.update_traces(textposition='top center', texttemplate='%{text:.2%}')
fig.update_yaxes(title='Return Rate (%)')

fig.show()

fig = px.line(data_completers_all_events_aggregated, 
              x='sequence', 
              y='return_rate_d1_relative_diff',
              color='set_completed',
              title='Relative Difference in Return Rate by Completers of Each Event (%)',
              width=1200,
              height=600,
              hover_data={'return_rate_d1_relative_diff': ':.2%'},
              text='return_rate_d1_relative_diff')

fig.update_traces(textposition='top center', texttemplate='%{text:.4%}')
fig.update_yaxes(title='Return Rate (%)')

fig.show()

#### Revenue

In [38]:
fig = px.line(data_completers_all_events, 
# Line chart of daily IAP revenue by completer cohort over calendar time
              x='dt', 
              y='iap_revenue',
              color='set_completed',
              title='Daily IAP Revenue by completers of each event',
              width=1200,
              height=600,
              hover_data={'iap_revenue': True, 'unique_users': True},
              category_orders={'set': custom_order})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

fig = px.line(data_completers_all_events, 
              x='dt', 
              y='ad_revenue',
              color='set_completed',
              title='Daily AD Revenue by completers of each event',
              width=1200,
              height=600,
              hover_data={'ad_revenue': True, 'unique_users': True},
              category_orders={'set': custom_order})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [39]:
fig = px.line(data_completers_all_events, 
# Line chart of IAP revenue by days since event start for each completer cohort
              x='days_since_event_start', 
              y='iap_revenue',
              color='set_completed+running',
              title='Daily IAP Revenue by completers of each event by days since event start',
              width=1200,
              height=600,
              hover_data={'iap_revenue': True, 'unique_users': True},
              category_orders={'set': custom_order})

#fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

fig = px.line(data_completers_all_events, 
              x='days_since_event_start', 
              y='ad_revenue',
              color='set_completed+running',
              title='Daily Ad Revenue by completers of each event by days since event start',
              width=1200,
              height=600,
              hover_data={'ad_revenue': True, 'unique_users': True},
              category_orders={'set': custom_order})

#fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

#### ARPU

In [40]:
fig = px.line(data_completers_all_events, 
# Line chart of daily ARPU by completer cohort over calendar time
              x='dt', 
              y='arpdau_completers',
              color='set_completed',
              title='Daily ARPU by completers of each event',
              width=1200,
              height=600,
              hover_data={'arpdau_completers': True, 'unique_users': True},
              category_orders={'liveops_event_definition_id': custom_order})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [41]:
fig = px.line(data_completers_all_events, 
# Line chart of ARPU by days since event start for each completer cohort
              x='days_since_event_start', 
              y='arpdau_completers',
              color='set_completed+running',
              title='Daily ARPU by Event for completers of each event by days since event start',
              width=1200,
              height=600,
              hover_data={'arpdau_completers': True, 'unique_users': True},
              category_orders={'liveops_event_definition_id': custom_order})

#fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [42]:
fig = px.bar(data_completers_all_events_aggregated, 
# Grouped bar chart of average ARPU by running event for each completer cohort
              x='set_running', 
              y='arpdau',
              color='set_completed',
              barmode='group',
              title='ARPU by Completers of Each Event',
              width=1200,
              height=600,
              hover_data={'arpdau': ':.2f'},
              category_orders={'set_completed': order, 'set_running': order},
              text='arpdau')

fig.update_traces(textposition='inside', texttemplate='%{text:.2f}')

#fig.update_yaxes(tickformat='.2%', range=[max(0, min_val - padding), max_val + padding])

fig.show()

In [43]:
# hide-output
# Calculates relative ARPU difference vs. the completer's own event
# Initialize the column if it doesn't exist
if 'arpdau_relative_diff' not in data_completers_all_events_aggregated.columns:
    data_completers_all_events_aggregated['arpdau_relative_diff'] = np.nan

# Calculate arpdau_relative_diff for all events
for event in order:
    event_data = data_completers_all_events_aggregated[
        data_completers_all_events_aggregated['set_completed'] == event
    ].copy()
    
    
    # Get the baseline value when set_running == set_completed
    baseline = event_data[event_data['set_running'] == event]['arpdau'].values
    
    if len(baseline) > 0:
        # Calculate relative diff for all rows in this event
        event_data['arpdau_relative_diff'] = (event_data['arpdau'] - baseline[0]) / baseline[0]
        
        # Update the main dataframe
        data_completers_all_events_aggregated.loc[
            data_completers_all_events_aggregated['set_completed'] == event,
            'arpdau_relative_diff'
        ] = event_data['arpdau_relative_diff'].values


data_completers_all_events_aggregated

,set_completed+running,set_completed,set_running,unique_users,iap_revenue,ad_revenue,return_rate_d1,return_rate_d7,return_rate_d14,return_rate_d28,arpdau,sequence,return_rate_d1_relative_diff,arpdau_relative_diff
0,JoesTastyTravels-JoesTastyTravels,JoesTastyTravels,JoesTastyTravels,98078,4.015253e+05,31558.668012,0.989520,0.982602,0.97114,0.938872,4.093938,0,0.000000,0.000000
1,JoesTastyTravels-WinterTales,JoesTastyTravels,WinterTales,90907,3.229032e+05,28359.428952,0.977246,0.950986,0.928065,0.892663,3.552017,1,-0.012403,-0.132372
2,JoesTastyTravels-AppletonLove,JoesTastyTravels,AppletonLove,80096,2.717684e+05,25387.324227,0.974712,0.951215,0.927628,0.882521,3.393033,2,-0.014965,-0.171206
3,JoesTastyTravels-Diorama,JoesTastyTravels,Diorama,70063,2.247907e+05,22619.674728,0.970433,0.949239,0.930544,0.90168,3.208408,3,-0.019289,-0.216303
4,JoesTastyTravels-ThroughTheAges,JoesTastyTravels,ThroughTheAges,63994,2.187906e+05,23117.604985,0.966632,0.945181,0.927018,0.895896,3.418924,4,-0.023130,-0.164881
5,JoesTastyTravels-Appletonians,JoesTastyTravels,NaN,27735,9.636694e+04,10049.989015,0.964751,0.946245,0.931769,NaN,3.474561,5,-0.025031,-0.151291
6,WinterTales-JoesTastyTravels,WinterTales,JoesTastyTravels,263963,5.586836e+05,61683.447166,0.984408,0.978942,0.977005,0.978748,2.116522,-1,-0.004873,-0.167504
7,WinterTales-WinterTales,WinterTales,WinterTales,308958,7.854895e+05,81827.946432,0.989229,0.981128,0.972335,0.944097,2.542383,0,0.000000,0.000000
8,WinterTales-AppletonLove,WinterTales,AppletonLove,287991,7.042660e+05,75686.212721,0.980672,0.954291,0.927171,0.877415,2.445445,1,-0.008650,-0.038129
9,WinterTales-Diorama,WinterTales,Diorama,246558,5.343153e+05,63610.067028,0.974414,0.95182,0.930444,0.895257,2.167098,2,-0.014976,-0.147611
10,WinterTales-ThroughTheAges,WinterTales,ThroughTheAges,220746,4.914201e+05,61537.282905,0.970662,0.949393,0.931245,0.89965,2.226179,3,-0.018769,-0.124373
11,WinterTales-Appletonians,WinterTales,NaN,95552,2.084276e+05,26296.816432,0.969211,0.94976,0.933786,NaN,2.181300,4,-0.020236,-0.142025
12,AppletonLove-JoesTastyTravels,AppletonLove,JoesTastyTravels,393493,5.975576e+05,78942.687742,0.977201,0.968193,0.963393,0.960203,1.518598,-2,-0.010618,-0.278233
13,AppletonLove-WinterTales,AppletonLove,WinterTales,454740,7.800607e+05,101662.995712,0.980862,0.974919,0.975881,0.980988,1.715399,-1,-0.006912,-0.184697
14,AppletonLove-AppletonLove,AppletonLove,AppletonLove,518506,1.090937e+06,132308.249207,0.987688,0.977755,0.963871,0.925148,2.104001,0,0.000000,0.000000
15,AppletonLove-Diorama,AppletonLove,Diorama,470968,8.731801e+05,116147.896034,0.975560,0.948218,0.921715,0.876503,1.854011,1,-0.012280,-0.118816
16,AppletonLove-ThroughTheAges,AppletonLove,ThroughTheAges,405215,7.403221e+05,102154.804673,0.968799,0.943702,0.922901,0.885179,1.826986,2,-0.019125,-0.131661
17,AppletonLove-Appletonians,AppletonLove,NaN,172402,3.057296e+05,42362.904264,0.966072,0.945783,0.928342,NaN,1.773353,3,-0.021886,-0.157152
18,Diorama-JoesTastyTravels,Diorama,JoesTastyTravels,293156,4.703317e+05,61076.001578,0.979300,0.971018,0.966524,0.962818,1.604374,-3,-0.009989,-0.300853
19,Diorama-WinterTales,Diorama,WinterTales,321922,5.799063e+05,73602.639941,0.982558,0.97571,0.974713,0.97641,1.801388,-2,-0.006695,-0.214999
20,Diorama-AppletonLove,Diorama,AppletonLove,358582,7.699048e+05,92606.118842,0.987055,0.983126,0.982179,0.982705,2.147082,-1,-0.002148,-0.064354
21,Diorama-Diorama,Diorama,Diorama,391419,8.982117e+05,111023.823605,0.989180,0.981234,0.970731,0.941513,2.294758,0,0.000000,0.000000
22,Diorama-ThroughTheAges,Diorama,ThroughTheAges,361655,8.073359e+05,104284.300195,0.977135,0.950782,0.926467,0.882442,2.232337,1,-0.012178,-0.027201
23,Diorama-Appletonians,Diorama,NaN,150348,3.204041e+05,41486.630244,0.972137,0.949381,0.927472,NaN,2.131083,2,-0.017230,-0.071325
24,ThroughTheAges-JoesTastyTravels,ThroughTheAges,JoesTastyTravels,180907,3.567158e+05,38858.567691,0.982646,0.97493,0.970484,0.965938,1.971819,-4,-0.007650,-0.388825
25,ThroughTheAges-WinterTales,ThroughTheAges,WinterTales,195766,4.265372e+05,46836.929100,0.985445,0.978837,0.977074,0.976971,2.178811,-3,-0.004823,-0.324666
26,ThroughTheAges-AppletonLove,ThroughTheAges,AppletonLove,210177,5.320312e+05,56625.420633,0.987942,0.983078,0.98137,0.979799,2.531348,-2,-0.002301,-0.215396
27,ThroughTheAges-Diorama,ThroughTheAges,Diorama,224889,5.955156e+05,65706.133246,0.989177,0.985722,0.985114,0.986754,2.648042,-1,-0.001055,-0.179226
28,ThroughTheAges-ThroughTheAges,ThroughTheAges,ThroughTheAges,238190,7.684661e+05,82077.616284,0.990221,0.981298,0.970779,0.953436,3.226274,0,0.000000,0.000000
29,ThroughTheAges-Appletonians,ThroughTheAges,NaN,105590,3.246685e+05,34344.193860,0.982288,0.962498,0.943012,NaN,3.074804,1,-0.008011,-0.046949

In [44]:
fig = px.line(data_completers_all_events_aggregated, 
# Line chart of relative ARPU difference (%) by running event across cohorts
              x='set_running', 
              y='arpdau_relative_diff',
              color='set_completed',
              title='Relative Difference in ARPU by Completers of Each Event (%)',
              width=1200,
              height=600,
              hover_data={'arpdau_relative_diff': ':.2%','unique_users': True,'iap_revenue': ':.0f'},
              category_orders={'set_completed': order, 'set_running': order},
              text='arpdau_relative_diff')

fig.update_traces(textposition='top center', texttemplate='%{text:.2%}%')
fig.update_yaxes(title='ARPDAU (%)')

fig.show()
fig = px.line(data_completers_all_events_aggregated, 
              x='sequence', 
              y='arpdau_relative_diff',
              color='set_completed',
              title='Relative Difference in ARPU by Completers of Each Event (%)',
              width=1200,
              height=600,
              hover_data={'arpdau_relative_diff': ':.2%','unique_users': True,'iap_revenue': ':.0f'},
              text='arpdau_relative_diff')

fig.update_traces(textposition='top center', texttemplate='%{text:.2%}%')
fig.update_yaxes(title='ARPDAU (%)')

fig.show()

# Prestigers

Analysis of users who reached Prestige (tier 2+) in Diorama — engagement funnel through tiers and revenue performance compared across events.

## Engagement

Distribution of Diorama users by max tier reached — overall and by day since event start — showing the funnel of how many pushed beyond tier 1.

In [54]:
# hide-output
# Filters data to Diorama and ThroughTheAges events for tier-reach analysis
data_diorama = data[data['liveops_event_definition_id'] == 'TimedAlbum-Diorama']
data_through_the_ages = data[data['liveops_event_definition_id'] == 'TimedAlbum-ThroughTheAges']

data_all_events = data[data['liveops_event_definition_id'].isin(['TimedAlbum-Diorama', 'TimedAlbum-ThroughTheAges','TimedAlbum-Appletonians'])]

data_prestigers = data_all_events.copy()

tier_reached_per_event = data_prestigers[data_prestigers.max_tier_reached<=10].groupby(['liveops_event_definition_id', 'max_tier_reached']).agg(
    users = ('user_id', 'nunique')
).reset_index()

# Calculate total users for each days_since_event_start
total_users_per_event = tier_reached_per_event.groupby('liveops_event_definition_id')['users'].sum().reset_index()
total_users_per_event.columns = ['liveops_event_definition_id', 'total_users_per_event']

# Merge to get total for each row
tier_reached_per_event = tier_reached_per_event.merge(total_users_per_event, on='liveops_event_definition_id', how='left')
# Calculate percentage
tier_reached_per_event['percentage_of_event_total'] = tier_reached_per_event['users'] / tier_reached_per_event['total_users_per_event']

tier_reached_per_event['max_tier_reached_str'] = tier_reached_per_event['max_tier_reached'].astype(str)

tier_reached_per_event['max_tier_reached_segment'] = pd.cut(
    tier_reached_per_event['max_tier_reached'],
    bins=[0, 1, 2, 10],
    labels=['1', '2', '3-10'])

tier_reached_per_event

,liveops_event_definition_id,max_tier_reached,users,total_users_per_event,percentage_of_event_total,max_tier_reached_str,max_tier_reached_segment
0,TimedAlbum-Appletonians,1,106800,106819,0.999822,1,1
1,TimedAlbum-Appletonians,2,19,106819,0.000178,2,2
2,TimedAlbum-Diorama,1,146295,156384,0.935486,1,1
3,TimedAlbum-Diorama,2,8329,156384,0.053260,2,2
4,TimedAlbum-Diorama,3,1098,156384,0.007021,3,3-10
5,TimedAlbum-Diorama,4,383,156384,0.002449,4,3-10
6,TimedAlbum-Diorama,5,160,156384,0.001023,5,3-10
7,TimedAlbum-Diorama,6,73,156384,0.000467,6,3-10
8,TimedAlbum-Diorama,7,23,156384,0.000147,7,3-10
9,TimedAlbum-Diorama,8,13,156384,0.000083,8,3-10
10,TimedAlbum-Diorama,9,7,156384,0.000045,9,3-10
11,TimedAlbum-Diorama,10,3,156384,0.000019,10,3-10
12,TimedAlbum-ThroughTheAges,1,132915,138076,0.962622,1,1
13,TimedAlbum-ThroughTheAges,2,4699,138076,0.034032,2,2
14,TimedAlbum-ThroughTheAges,3,393,138076,0.002846,3,3-10
15,TimedAlbum-ThroughTheAges,4,49,138076,0.000355,4,3-10
16,TimedAlbum-ThroughTheAges,5,9,138076,0.000065,5,3-10
17,TimedAlbum-ThroughTheAges,6,4,138076,0.000029,6,3-10
18,TimedAlbum-ThroughTheAges,7,3,138076,0.000022,7,3-10
19,TimedAlbum-ThroughTheAges,8,3,138076,0.000022,8,3-10
20,TimedAlbum-ThroughTheAges,10,1,138076,0.000007,10,3-10

In [55]:
tier_segment_reached_per_event = tier_reached_per_event.groupby(['liveops_event_definition_id', 'max_tier_reached_segment'], observed=True).agg(
    users = ('users', 'sum'),
    total_users_per_event = ('total_users_per_event', 'first')
).reset_index() 

tier_segment_reached_per_event

,liveops_event_definition_id,max_tier_reached_segment,users,total_users_per_event
0,TimedAlbum-Appletonians,1,106800,106819
1,TimedAlbum-Appletonians,2,19,106819
2,TimedAlbum-Diorama,1,146295,156384
3,TimedAlbum-Diorama,2,8329,156384
4,TimedAlbum-Diorama,3-10,1760,156384
5,TimedAlbum-ThroughTheAges,1,132915,138076
6,TimedAlbum-ThroughTheAges,2,4699,138076
7,TimedAlbum-ThroughTheAges,3-10,462,138076

In [56]:
# Stacked bar chart of user percentage by max tier reached per event
fig = px.bar(tier_reached_per_event, 
              x='liveops_event_definition_id', 
              y='percentage_of_event_total',
              color='max_tier_reached_str',
              title='% users by tier reached per event',
              width=600,
              height=600,
              custom_data=['users'],
              category_orders={'max_tier_reached_str': sorted(tier_reached_per_event['max_tier_reached_str'].unique())})

fig.update_traces(hovertemplate='<b>Days Since Event Start:</b> %{x}<br><b>Max Tier Reached:</b> %{fullData.name}<br><b>Percentage:</b> %{y:.2%}<br><b>Users:</b> %{customdata[0]}<extra></extra>')
fig.update_yaxes(tickformat='.2%')
fig.update_layout(legend_title='Max Tier Reached')
fig.show()

In [57]:
# hide-output
# Aggregates tier distribution by days since event start for the latest event
tier_reached_daily = data_prestigers[data_prestigers.max_tier_reached<=10].groupby(['liveops_event_definition_id', 'days_since_event_start', 'max_tier_reached']).agg(
    users = ('user_id', 'nunique')
).reset_index()

# Calculate total users for each days_since_event_start
total_users_per_day = tier_reached_daily.groupby(['liveops_event_definition_id','days_since_event_start'])['users'].sum().reset_index()
total_users_per_day.columns = ['liveops_event_definition_id','days_since_event_start', 'total_users_per_day']

# Merge to get total for each row
tier_reached_daily = tier_reached_daily.merge(total_users_per_day, on=['liveops_event_definition_id','days_since_event_start'], how='left')
# Calculate percentage
tier_reached_daily['percentage_of_day_total'] = tier_reached_daily['users'] / tier_reached_daily['total_users_per_day']

tier_reached_daily['max_tier_reached_str'] = tier_reached_daily['max_tier_reached'].astype(str) 
tier_reached_daily

,liveops_event_definition_id,days_since_event_start,max_tier_reached,users,total_users_per_day,percentage_of_day_total,max_tier_reached_str
0,TimedAlbum-Appletonians,0,1,60477,60477,1.000000,1
1,TimedAlbum-Appletonians,1,1,64721,64721,1.000000,1
2,TimedAlbum-Appletonians,2,1,64373,64373,1.000000,1
3,TimedAlbum-Appletonians,3,1,67991,67991,1.000000,1
4,TimedAlbum-Appletonians,4,1,69840,69840,1.000000,1
...,...,...,...,...,...,...,...
367,TimedAlbum-ThroughTheAges,40,2,18,72257,0.000249,2
368,TimedAlbum-ThroughTheAges,41,1,71245,71248,0.999958,1
369,TimedAlbum-ThroughTheAges,41,2,3,71248,0.000042,2
370,TimedAlbum-ThroughTheAges,42,1,70110,70111,0.999986,1
371,TimedAlbum-ThroughTheAges,42,2,1,70111,0.000014,2

In [58]:
fig = px.bar(tier_reached_daily, 
# Stacked bar chart of tier distribution over days since event start
              x='days_since_event_start', 
              y='percentage_of_day_total',
              color='max_tier_reached_str',
              title='% users by tier reached over days since event start',
              facet_row = 'liveops_event_definition_id',
              width=1200,
              height=1000,
              custom_data=['users'],
              category_orders={'max_tier_reached_str': sorted(tier_reached_daily['max_tier_reached_str'].unique())})

fig.update_traces(hovertemplate='<b>Days Since Event Start:</b> %{x}<br><b>Max Tier Reached:</b> %{fullData.name}<br><b>Percentage:</b> %{y:.2%}<br><b>Users:</b> %{customdata[0]}<extra></extra>')
fig.update_yaxes(tickformat='.2%')
fig.update_layout(legend_title='Max Tier Reached')
fig.show()

## Revenue

ARPDAU and total IAP/ad revenue for prestige users over time and by days since event start, with a 7-day rolling average to smooth noise.

In [59]:
# hide-output
# Aggregates revenue metrics for prestige users by date and event
data_revenue_prestigers = data_extended[((data_extended['reached_prestige_diorama_user_id'].notna()) | (data_extended['reached_prestige_throughtheages_user_id'].notna())) & (data_extended['liveops_event_definition_id']!='NoTimedAlbum')].groupby(['dt', 'liveops_event_definition_id']).agg(
    unique_users=('user_id', 'nunique'),
    iap_revenue=('gross_usd_iap_revenue', 'sum'),
    ad_revenue=('gross_usd_ad_revenue', 'sum')
    ).reset_index()

data_revenue_prestigers['arpdau'] = data_revenue_prestigers['iap_revenue'] / (data_revenue_prestigers['unique_users'] * 1)  # Assuming 1 day for ARPDAU

data_revenue_prestigers

,dt,liveops_event_definition_id,unique_users,iap_revenue,ad_revenue,arpdau
0,2025-11-03,TimedAlbum-JoesTastyTravels,3358,5697.960253,659.100327,1.696832
1,2025-11-04,TimedAlbum-JoesTastyTravels,3503,5580.136184,701.811259,1.592959
2,2025-11-05,TimedAlbum-JoesTastyTravels,3512,5831.457798,686.379318,1.660438
3,2025-11-06,TimedAlbum-JoesTastyTravels,3508,5969.368523,664.520314,1.701644
4,2025-11-07,TimedAlbum-JoesTastyTravels,3522,9810.878549,682.355740,2.785599
...,...,...,...,...,...,...
230,2026-06-12,TimedAlbum-Appletonians,8008,11099.596559,1928.739264,1.386064
231,2026-06-13,TimedAlbum-Appletonians,7922,14014.379480,2071.820729,1.769046
232,2026-06-14,TimedAlbum-Appletonians,7952,14911.854891,2316.580426,1.875233
233,2026-06-15,TimedAlbum-Appletonians,7957,15471.802843,2118.052951,1.944427
234,2026-06-16,TimedAlbum-Appletonians,8004,19390.704855,2115.148065,2.422627

In [60]:
fig = px.line(data_revenue_prestigers, 
# Line chart of daily IAP revenue from prestige users by event
              x='dt', 
              y='iap_revenue',
              color='liveops_event_definition_id',
              title='Daily IAP Revenue by Event',
              width=1200,
              height=600,
              hover_data={'iap_revenue': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [61]:
fig = px.line(data_revenue_prestigers, 
# Line chart of daily ARPU from prestige users by event
              x='dt', 
              y='arpdau',
              color='liveops_event_definition_id',
              title='Daily ARPU by Event',
              width=1200,
              height=600,
              hover_data={'iap_revenue': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [62]:
# hide-output
# Aggregates prestige user revenue metrics by days since event start
data_revenue_prestigers_dse = data_extended[(data_extended['reached_prestige_user_id'].notna())& (data_extended['liveops_event_definition_id']!='NoTimedAlbum')].groupby(['days_since_event_start', 'liveops_event_definition_id']).agg(
    unique_users=('user_id', 'nunique'),
    iap_revenue=('gross_usd_iap_revenue', 'sum'),
    ad_revenue=('gross_usd_ad_revenue', 'sum')
    ).reset_index()

data_revenue_prestigers_dse['arpdau'] = data_revenue_prestigers_dse['iap_revenue'] / (data_revenue_prestigers_dse['unique_users'] * 1)  # Assuming 1 day for ARPDAU

data_revenue_prestigers_dse

KeyError: 'reached_prestige_user_id'

In [ ]:
data_revenue_prestigers_dse['arpdau_lag7'] = data_revenue_prestigers_dse.groupby('liveops_event_definition_id')['arpdau'].transform(lambda x: x.rolling(window=7, min_periods=1).mean())
# Calculates 7-day rolling ARPU average and reshapes data for dual-trace plot

# Reshape data for plotly (separate traces for arpdau and arpdau_lag7)
fig = go.Figure()

for event in custom_order:
    if event in data_revenue_prestigers_dse['liveops_event_definition_id'].values:
        event_data = data_revenue_prestigers_dse[data_revenue_prestigers_dse['liveops_event_definition_id'] == event]
        
        fig.add_trace(go.Scatter(
            x=event_data['days_since_event_start'],
            y=event_data['arpdau'],
            mode='lines',
            name=f'{event}',
            hovertemplate='<b>Days Since Event:</b> %{x}<br><b>ARPDAU:</b> %{y:.2f}<extra></extra>'
        ))
        
        fig.add_trace(go.Scatter(
            x=event_data['days_since_event_start'],
            y=event_data['arpdau_lag7'],
            mode='lines',
            name=f'{event} (7-day avg)',
            line=dict(dash='dash'),
            hovertemplate='<b>Days Since Event:</b> %{x}<br><b>ARPDAU 7-day avg:</b> %{y:.2f}<extra></extra>'
        ))

fig.update_layout(
    title='Daily ARPU by Event with 7-day Running Average',
    width=1200,
    height=600,
    xaxis_title='Days Since Event Start',
    yaxis_title='ARPDAU'
)

fig.show()

# Economy

Analysis of currency flows (coins, energy, gems) across the full population and for completer cohorts. Focuses on whether completers are inflating gem balances relative to non-completers.

<!-- hide -->
### Prepare data

Adds a `completer_any_flag` to the economy dataframe (1 = completed any Timed Album, 0 = did not), enabling completer vs. non-completer segmentation throughout the section.

In [ ]:
# hide-output
# Flags economy users as completers (1) or non-completers (0) for segmentation
data_econ['completer_any_flag'] = data_econ['user_id'].isin(users_completers_any).astype(int)
data_econ['completer_any_flag'] = data_econ['completer_any_flag'].astype('category')
data_econ['balance_end'] = data_econ['balance_end'].astype(float)
data_econ

,dt,user_id,currency,balance_start,balance_end,n_economy_inflow,n_economy_outflow,completer_any_flag
0,2025-11-01,8523463ECBFA0EF6,energy,100.000000000,0.0,53,144,0
1,2025-11-01,5EEE6CADDE44541B,energy,100.000000000,2.0,290,648,0
2,2025-11-01,E68A80CB8CB6DBA8,coins,131749.000000000,132908.0,1226,0,1
3,2025-11-01,63441E515FBEB55,gems,61.000000000,51.0,<NA>,10,0
4,2025-11-01,3454D028CA05699F,energy,100.000000000,0.0,75,183,0
...,...,...,...,...,...,...,...,...
57417908,2026-05-26,CF07F359AF728274,energy,66.000000000,1430.0,3300,1997,1
57417909,2026-05-26,B8C2D676452D218B,coins,867.000000000,1392.0,526,0,1
57417910,2026-05-26,9CEEE7CAE279E248,coins,132.000000000,1410.0,1279,0,0
57417911,2026-05-26,7C8474C1F54E11DA,energy,100.000000000,0.0,205,397,0
57417912,2026-05-26,35A7A21B50782DBF,coins,24.000000000,33.0,12,0,0

In [ ]:
# hide-output
# Inspects data types of economy dataframe columns
data_econ.dtypes

dt                      dbdate
user_id                 object
currency                object
balance_start           object
balance_end            float64
n_economy_inflow         Int64
n_economy_outflow        Int64
completer_any_flag    category
dtype: object

In [ ]:
# hide-output
# using the code below create a dataframe that contails the p90, p50 and p10 for each currency by dt

econ_inflow_percentiles = data_econ.groupby(['dt','currency'])['n_economy_inflow'].quantile([0.9, 0.5, 0.1]).unstack().reset_index()
econ_outflow_percentiles = data_econ.groupby(['dt','currency'])['n_economy_outflow'].quantile([0.9, 0.5, 0.1]).unstack().reset_index()
econ_balance_end_percentiles = data_econ.groupby(['dt','currency'])['balance_end'].quantile([0.9, 0.5, 0.1]).unstack().reset_index()

# merge the inflow and outflow percentiles
econ_percentiles = pd.DataFrame()
econ_percentiles = pd.merge(econ_inflow_percentiles, econ_outflow_percentiles, on=['dt', 'currency'])
econ_percentiles = pd.merge(econ_percentiles, econ_balance_end_percentiles, on=['dt', 'currency'])

# rename dataframe columns to include the currency and the percentile
econ_percentiles.columns = ['dt', 'currency', 'p10_n_economy_inflow', 'p50_n_economy_inflow', 'p90_n_economy_inflow', 'p10_n_economy_outflow', 'p50_n_economy_outflow', 'p90_n_economy_outflow', 'p10_balance_end', 'p50_balance_end', 'p90_balance_end']

econ_energy_percentiles = econ_percentiles[econ_percentiles['currency'] == 'energy']
econ_gems_percentiles = econ_percentiles[econ_percentiles['currency'] == 'gems']
econ_coins_percentiles = econ_percentiles[econ_percentiles['currency'] == 'coins']

econ_percentiles

,dt,currency,p10_n_economy_inflow,p50_n_economy_inflow,p90_n_economy_inflow,p10_n_economy_outflow,p50_n_economy_outflow,p90_n_economy_outflow,p10_balance_end,p50_balance_end,p90_balance_end
0,2025-11-01,coins,3005.0,619.0,87.0,2120.0,250.0,0.0,147896.8,240.0,26.0
1,2025-11-01,energy,712.0,210.0,15.0,1029.0,379.0,100.0,55.0,1.0,0.0
2,2025-11-01,gems,48.0,8.0,1.0,54.0,10.0,0.0,686.0,53.0,4.0
3,2025-11-02,coins,2709.0,603.0,86.0,2020.0,260.0,0.0,141541.8,229.0,25.3
4,2025-11-02,energy,691.0,215.0,15.0,1001.0,388.0,100.0,54.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
616,2026-05-25,energy,995.0,315.0,30.0,1356.0,530.0,110.0,82.0,1.0,0.0
617,2026-05-25,gems,62.0,16.0,1.0,70.0,10.0,0.0,1219.0,65.0,5.0
618,2026-05-26,coins,4189.0,926.0,121.0,2530.0,260.0,0.0,437398.0,406.0,43.0
619,2026-05-26,energy,855.0,280.0,25.0,1230.0,501.0,110.0,80.0,1.0,0.0
620,2026-05-26,gems,62.0,8.0,1.0,85.0,10.0,0.0,1195.0,56.0,4.0

In [ ]:
# hide-output
# Aggregates economy metrics by date and currency: users, ending balance, inflows, outflows
# all users
econ_agg = data_econ.groupby(['dt','currency',]).agg(
    unique_users=('user_id', 'nunique'),
    avg_ending_balance=('balance_end', 'mean'),
    sum_inflows=('n_economy_inflow', 'sum'),
    sum_outflows=('n_economy_outflow', 'sum'),
).reset_index()

econ_agg['avg_inflows'] = econ_agg['sum_inflows'] / econ_agg['unique_users']
econ_agg['avg_outflows'] = econ_agg['sum_outflows'] / econ_agg['unique_users']

econ_agg['net_flow'] = econ_agg['avg_inflows'] - econ_agg['avg_outflows']

econ_energy_agg = econ_agg[econ_agg['currency'] == 'energy']
econ_gems_agg = econ_agg[econ_agg['currency'] == 'gems']
econ_coins_agg = econ_agg[econ_agg['currency'] == 'coins']


# completers users
econ_agg_completers = data_econ[data_econ['completer_any_flag'] == 1].groupby(['dt','currency']).agg(
    unique_users=('user_id', 'nunique'),
    avg_ending_balance=('balance_end', 'mean'),
    sum_inflows=('n_economy_inflow', 'sum'),
    sum_outflows=('n_economy_outflow', 'sum'),
).reset_index()

econ_agg_completers['avg_inflows'] = econ_agg_completers['sum_inflows'] / econ_agg_completers['unique_users']
econ_agg_completers['avg_outflows'] = econ_agg_completers['sum_outflows'] / econ_agg_completers['unique_users']

econ_agg_completers['net_flow'] = econ_agg_completers['avg_inflows'] - econ_agg_completers['avg_outflows']

econ_energy_agg_completers = econ_agg_completers[econ_agg_completers['currency'] == 'energy']
econ_gems_agg_completers = econ_agg_completers[econ_agg_completers['currency'] == 'gems']
econ_coins_agg_completers = econ_agg_completers[econ_agg_completers['currency'] == 'coins']

# non completers users
econ_agg_non_completers = data_econ[data_econ['completer_any_flag'] == 0].groupby(['dt','currency']).agg(
    unique_users=('user_id', 'nunique'),
    avg_ending_balance=('balance_end', 'mean'),
    sum_inflows=('n_economy_inflow', 'sum'),
    sum_outflows=('n_economy_outflow', 'sum'),
).reset_index()

econ_agg_non_completers['avg_inflows'] = econ_agg_non_completers['sum_inflows'] / econ_agg_non_completers['unique_users']
econ_agg_non_completers['avg_outflows'] = econ_agg_non_completers['sum_outflows'] / econ_agg_non_completers['unique_users']

econ_agg_non_completers['net_flow'] = econ_agg_non_completers['avg_inflows'] - econ_agg_non_completers['avg_outflows']

econ_energy_agg_non_completers = econ_agg_non_completers[econ_agg_non_completers['currency'] == 'energy']
econ_gems_agg_non_completers = econ_agg_non_completers[econ_agg_non_completers['currency'] == 'gems']
econ_coins_agg_non_completers = econ_agg_non_completers[econ_agg_non_completers['currency'] == 'coins']


# with completer non-completer flag
econ_agg_flagged = data_econ.groupby(['dt','currency','completer_any_flag'], observed=True).agg(
    unique_users=('user_id', 'nunique'),
    avg_ending_balance=('balance_end', 'mean'),
    sum_inflows=('n_economy_inflow', 'sum'),
    sum_outflows=('n_economy_outflow', 'sum'),
).reset_index()

econ_agg_flagged['avg_inflows'] = econ_agg_flagged['sum_inflows'] / econ_agg_flagged['unique_users']
econ_agg_flagged['avg_outflows'] = econ_agg_flagged['sum_outflows'] / econ_agg_flagged['unique_users']

econ_agg_flagged['net_flow'] = econ_agg_flagged['avg_inflows'] - econ_agg_flagged['avg_outflows']

econ_energy_agg_flagged = econ_agg_flagged[econ_agg_flagged['currency'] == 'energy']
econ_gems_agg_flagged = econ_agg_flagged[econ_agg_flagged['currency'] == 'gems']
econ_coins_agg_flagged = econ_agg_flagged[econ_agg_flagged['currency'] == 'coins']

econ_agg

,dt,currency,unique_users,avg_ending_balance,sum_inflows,sum_outflows,avg_inflows,avg_outflows,net_flow
0,2025-11-01,coins,114203,49553.098430,131621579,82757828,1152.522955,724.655464,427.86749
1,2025-11-01,energy,116070,38801.459507,33014671,56156503,284.437589,483.815827,-199.378237
2,2025-11-01,gems,81951,307.656197,2550218,2749904,31.118815,33.555466,-2.436651
3,2025-11-02,coins,118834,73830.843715,126828349,86157108,1067.273247,725.020684,342.252562
4,2025-11-02,energy,120869,37592.217707,33792854,58035860,279.582474,480.155044,-200.57257
...,...,...,...,...,...,...,...,...,...
616,2026-05-25,energy,78980,167.428058,34474397,52732363,436.495277,667.667296,-231.172018
617,2026-05-25,gems,56164,465.119899,2916420,2559137,51.926857,45.565433,6.361424
618,2026-05-26,coins,76567,109910.839618,130313266,70801276,1701.950788,924.69701,777.253778
619,2026-05-26,energy,77994,54729.190617,30029871,48383240,385.027964,620.345668,-235.317704
620,2026-05-26,gems,59110,455.018254,2745071,2965474,46.440044,50.168736,-3.728692

## Gems

Deep-dive into gem currency flows — the primary currency of interest for the prestige question. Covers ending balances, net flow, inflow vs. outflow, and the completer vs. non-completer split.

### Users

Daily count of users with gem economy activity, split by completer flag — shows the relative size of the completer population in the gem economy.

In [ ]:
fig = px.bar(econ_gems_agg_flagged, 
# Stacked bar chart of daily gem economy users segmented by completer flag
              x='dt', 
              y='unique_users',
              color='completer_any_flag',
              title='Gems unique users by day',
              width=1200,
              height=600,
              hover_data={'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

### Ending balances

Average and percentile (p10/p50/p90) gem ending balances over time for the full population, plus a distribution of total gem balance per user across the whole period.

In [ ]:
fig = px.line(econ_gems_agg, 
# Line chart of average gem ending balance over time
              x='dt', 
              y='avg_ending_balance',
              #color='currency',
              title='Gems average ending balance by day',
              width=1200,
              height=600,
              hover_data={'avg_ending_balance': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

fig = px.line(econ_gems_agg_completers, 
              x='dt', 
              y='avg_ending_balance',
              #color='currency',
              title='Gems average ending balance by day (Only-completers)',
              width=1200,
              height=600,
              hover_data={'avg_ending_balance': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

fig = px.line(econ_gems_agg_non_completers, 
              x='dt', 
              y='avg_ending_balance',
              #color='currency',
              title='Gems average ending balance by day (Non-completers)',
              width=1200,
              height=600,
              hover_data={'avg_ending_balance': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

### Ending Balances percentiles

Analyzing P90, P50(median) and P10 percentiles for the gems ending balance

In [ ]:
# Melt the percentiles data for easier plotting
# Reshapes gem percentile data from wide to long format and plots P10/P50/P90 lines
econ_gems_percentiles_melted = econ_gems_percentiles.melt(
    id_vars=['dt'],
    value_vars=['p10_balance_end', 'p50_balance_end', 'p90_balance_end'],
    var_name='percentile',
    value_name='balance'
)

fig = px.line(econ_gems_percentiles_melted, 
              x='dt', 
              y='balance',
              color='percentile',
              title='Gems ending balance percentiles by day',
              width=1200,
              height=600,
              labels={'percentile': 'Percentile', 'balance': 'Balance'},
              category_orders={'percentile': ['p10_balance_end', 'p50_balance_end', 'p90_balance_end']})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [ ]:
# hide-output
# Calculates total inflow, outflow, and net flow per user across the full analysis period
distribution_date = pd.DataFrame()
distribution_data = data_econ.groupby(['user_id','currency']).agg(
    total_inflow=('n_economy_inflow', 'sum'),
    total_outflow=('n_economy_outflow', 'sum'),
    balance_end=('balance_end', 'mean'),
).reset_index()

distribution_data_gems = distribution_data[distribution_data['currency'] == 'gems']

distribution_data

                  user_id currency  total_inflow  total_outflow  balance_end
0        100006BF6559BF99    coins           252            224    28.000000
1        100006BF6559BF99   energy           397            505     0.000000
2        100006BF6559BF99     gems             8             30    28.000000
3        10003F6FA8F5957E    coins         65295          66494   109.167665
4        10003F6FA8F5957E   energy         28008          62019     5.380952
...                   ...      ...           ...            ...          ...
1956614  FFFFF4ACE971353A    coins          3470           3490   121.857143
1956615  FFFFF4ACE971353A   energy          2557           3927    28.571429
1956616  FFFFF4ACE971353A     gems            77             70    16.666667
1956617  FFFFF67B4ED7017A    coins             9              5     4.000000
1956618  FFFFF67B4ED7017A   energy             0              6    95.000000

[1956619 rows x 5 columns]

In [ ]:
# hide-output
# Filters gem balance distribution to <= 1000 and prepares data for histogram
# Pre-aggregate gems data by balance_end ranges
gems_data = distribution_data_gems[distribution_data_gems['balance_end']<=1000].copy()
gems_data['balance_end'] = pd.to_numeric(gems_data['balance_end'], errors='coerce')

# Create histogram data with 100 bins
gems_hist, bin_edges = np.histogram(gems_data['balance_end'].dropna(), bins=500)

# Create aggregated dataframe
gems_agg = pd.DataFrame({
    'balance_end': (bin_edges[:-1] + bin_edges[1:]) / 2,  # bin centers
    'count': gems_hist
})

# Calculate statistics
p10 = gems_data['balance_end'].quantile(0.1)
p50 = gems_data['balance_end'].quantile(0.5)
p90 = gems_data['balance_end'].quantile(0.9)
mean_balance = gems_data['balance_end'].mean()

# Create histogram
fig = px.bar(
    gems_agg,
    x='balance_end',
    y='count',
    title='Gems Ending Balance Distribution (with P10, P50, P90, and Mean)',
    labels={'balance_end': 'Ending Balance', 'count': 'Number of Users'},
    width=1200,
    height=600,
)

# Add vertical lines for percentiles and mean
fig.add_vline(x=p10, line_dash='dash', line_color='blue', annotation_text='P10', annotation_position='top')
fig.add_vline(x=p50, line_dash='dash', line_color='green', annotation_text='P50 (Median)', annotation_position='top')
fig.add_vline(x=p90, line_dash='dash', line_color='red', annotation_text='P90', annotation_position='top')
fig.add_vline(x=mean_balance, line_dash='dot', line_color='purple', annotation_text='Mean', annotation_position='top')

fig.update_layout(showlegend=False)

fig.show()

### Net flow

Daily net gem flow (inflows − outflows) for the full population — positive values indicate net gem accumulation, negative indicate net spending.

In [ ]:
fig = px.line(econ_gems_agg, 
# Line chart of daily net gem flow (inflows minus outflows) over time
              x='dt', 
              y='net_flow',
              #color='currency',
              title='Gems net flow by day',
              width=1200,
              height=600,
              hover_data={'net_flow': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

# add horizontal line at y=0
fig.add_hline(y=0, line_dash="dash", line_color="gray") 

fig.show()

fig = px.line(econ_gems_agg_completers, 
              x='dt', 
              y='net_flow',
              #color='currency',
              title='Gems net flow by day (Only-Completers)',
              width=1200,
              height=600,
              hover_data={'net_flow': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

# add horizontal line at y=0
fig.add_hline(y=0, line_dash="dash", line_color="gray") 

fig.show()

fig = px.line(econ_gems_agg_non_completers, 
              x='dt', 
              y='net_flow',
              #color='currency',
              title='Gems net flow by day (Non-completers)',
              width=1200,
              height=600,
              hover_data={'net_flow': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

# add horizontal line at y=0
fig.add_hline(y=0, line_dash="dash", line_color="gray") 

fig.show()

### Inflow vs Outflow

Average gem inflows and outflows plotted side-by-side to show whether activity is driven by earning or spending, and how the two move together over time.

In [ ]:
# Melt the dataframe to have inflows and outflows as separate rows
# Reshapes gem inflow/outflow to long format and plots side-by-side comparison
econ_gems_melted = econ_gems_agg.melt(
    id_vars=['dt', 'unique_users'], 
    value_vars=['avg_inflows', 'avg_outflows'],
    var_name='flow_type',
    value_name='amount'
)

fig = px.line(econ_gems_melted, 
              x='dt', 
              y='amount',
              color='flow_type',
              title='Gems average inflows and outflows by day',
              width=1200,
              height=600,
              hover_data={'amount': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

# Melt the dataframe to have inflows and outflows as separate rows
econ_gems_melted_completers = econ_gems_agg_completers.melt(
    id_vars=['dt', 'unique_users'], 
    value_vars=['avg_inflows', 'avg_outflows'],
    var_name='flow_type',
    value_name='amount'
)

fig = px.line(econ_gems_melted_completers, 
              x='dt', 
              y='amount',
              color='flow_type',
              title='Gems average inflows and outflows by day (Only-Completers)',
              width=1200,
              height=600,
              hover_data={'amount': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

# Melt the dataframe to have inflows and outflows as separate rows
econ_gems_melted_non_completers = econ_gems_agg_non_completers.melt(
    id_vars=['dt', 'unique_users'], 
    value_vars=['avg_inflows', 'avg_outflows'],
    var_name='flow_type',
    value_name='amount'
)

fig = px.line(econ_gems_melted_non_completers, 
              x='dt', 
              y='amount',
              color='flow_type',
              title='Gems average inflows and outflows by day (Non-Completers)',
              width=1200,
              height=600,
              hover_data={'amount': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

<!-- hide --> 
# Economy by completer cohort (work in progress)

Breaks down gem economy metrics (ending balance, inflows, outflows) separately for each completer cohort, allowing comparison of gem behaviour across events.

<!-- hide --> 
## Completers for each event

Tracks average gem ending balance, inflows, and outflows over time for each completer cohort (JoesTastyTravels, WinterTales, AppletonLove, Diorama), and compares completers vs. non-completers.

In [ ]:
# hide-output
# Create a loop to iterate through all events and aggregate results
events = custom_order
user_sets = [users_completer_JoesTastyTravels, users_completer_WinterTales, users_completer_AppletonLove, users_completer_Diorama, users_completer_ThroughTheAges]
#user_sets = [users_near_completer_JoesTastyTravels, users_near_completer_WinterTales, users_near_completer_AppletonLove, users_near_completer_Diorama, users_near_completer_ThroughTheAges]
user_set_names = ['JoesTastyTravels', 'WinterTales', 'AppletonLove', 'Diorama', 'ThroughTheAges']
filter_mask = ['JoesTastyTravels', 'WinterTales', 'AppletonLove', 'Diorama','ThroughTheAges']
results_completers_list = []
results_non_completers_list = []

for set, set_name in zip(user_sets, user_set_names):
    econ_completers_data = data_econ[(data_econ['user_id'].isin(set))]

    econ_completers_aggregated = econ_completers_data.groupby(['dt','currency']).agg(
        unique_users=('user_id', 'nunique'),
        avg_ending_balance=('balance_end', 'mean'),
        avg_inflows=('n_economy_inflow', 'mean'),
        avg_outflows=('n_economy_outflow', 'mean'),
    ).reset_index()

    econ_completers_aggregated['set_completed'] = set_name

    econ_non_completers_data = data_econ[~data_econ['user_id'].isin(set)]

    econ_non_completers_aggregated = econ_non_completers_data.groupby(['dt','currency']).agg(
        unique_users=('user_id', 'nunique'),
        avg_ending_balance=('balance_end', 'mean'),
        avg_inflows=('n_economy_inflow', 'mean'),
        avg_outflows=('n_economy_outflow', 'mean'),
    ).reset_index()

    econ_non_completers_aggregated['set_completed'] = set_name

    results_completers_list.append(econ_completers_aggregated)
    results_non_completers_list.append(econ_non_completers_aggregated)

econ_completers_all_events = pd.concat(results_completers_list, ignore_index=True)
econ_non_completers_all_events = pd.concat(results_non_completers_list, ignore_index=True)

econ_completers_all_events = econ_completers_all_events[econ_completers_all_events['set_completed'].isin(filter_mask)]
econ_non_completers_all_events = econ_non_completers_all_events[econ_non_completers_all_events['set_completed'].isin(filter_mask)]

econ_completers_all_events

,dt,currency,unique_users,avg_ending_balance,avg_inflows,avg_outflows,set_completed
0,2025-11-01,coins,2094,235751.076886,3403.244625,1285.267431,JoesTastyTravels
1,2025-11-01,energy,2098,36.131554,689.850602,1018.352717,JoesTastyTravels
2,2025-11-01,gems,1953,891.100358,252.472122,184.845878,JoesTastyTravels
3,2025-11-02,coins,2113,237235.461903,2953.768102,1135.936583,JoesTastyTravels
4,2025-11-02,energy,2116,31.526465,625.657279,973.316163,JoesTastyTravels
...,...,...,...,...,...,...,...
3100,2026-05-25,energy,5550,184.928468,1308.697349,1635.195315,ThroughTheAges
3101,2026-05-25,gems,5313,1958.639375,495.084722,257.860343,ThroughTheAges
3102,2026-05-26,coins,5505,565215.127884,5793.819255,1675.132062,ThroughTheAges
3103,2026-05-26,energy,5517,154.547036,1165.469459,1526.999275,ThroughTheAges
3104,2026-05-26,gems,5356,2029.493652,434.787966,288.093913,ThroughTheAges

In [ ]:
# hide-output
# Splits aggregated economy data into separate dataframes by currency type
econ_completers_energy_agg = econ_completers_all_events[econ_completers_all_events['currency'] == 'energy']
econ_completers_gems_agg = econ_completers_all_events[econ_completers_all_events['currency'] == 'gems']
econ_completers_coins_agg = econ_completers_all_events[econ_completers_all_events['currency'] == 'coins']

econ_noncompleters_energy_agg = econ_non_completers_all_events[econ_non_completers_all_events['currency'] == 'energy']
econ_noncompleters_gems_agg = econ_non_completers_all_events[econ_non_completers_all_events['currency'] == 'gems']
econ_noncompleters_coins_agg = econ_non_completers_all_events[econ_non_completers_all_events['currency'] == 'coins']



econ_completers_gems_agg

,dt,currency,unique_users,avg_ending_balance,avg_inflows,avg_outflows,set_completed
2,2025-11-01,gems,1953,891.100358,252.472122,184.845878,JoesTastyTravels
5,2025-11-02,gems,1971,862.493151,208.212099,154.093354,JoesTastyTravels
8,2025-11-03,gems,2068,885.570116,245.655556,189.468569,JoesTastyTravels
11,2025-11-04,gems,2069,875.826970,223.474845,192.301595,JoesTastyTravels
14,2025-11-05,gems,2087,886.870149,186.665641,163.252995,JoesTastyTravels
...,...,...,...,...,...,...,...
3092,2026-05-22,gems,5384,1800.815379,354.280429,197.042162,ThroughTheAges
3095,2026-05-23,gems,5316,1815.652558,320.136121,204.018999,ThroughTheAges
3098,2026-05-24,gems,5332,1900.222806,386.772491,210.111403,ThroughTheAges
3101,2026-05-25,gems,5313,1958.639375,495.084722,257.860343,ThroughTheAges
3104,2026-05-26,gems,5356,2029.493652,434.787966,288.093913,ThroughTheAges

In [ ]:
fig = px.line(econ_completers_gems_agg, 
# Line chart of average gem ending balance over time by completer cohort
              x='dt', 
              y='avg_ending_balance',
              color='set_completed',
              title='Gems average ending balance by day',
              width=1200,
              height=600,
              hover_data={'avg_ending_balance': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

fig = px.line(econ_noncompleters_gems_agg, 
              x='dt', 
              y='avg_ending_balance',
              color='set_completed',
              title='Gems average ending balance by day',
              width=1200,
              height=600,
              hover_data={'avg_ending_balance': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)

fig.show()

In [ ]:
# Add set to legends for completers vs non-completers gems comparison
# Reshapes gem inflow/outflow for completer vs. non-completer comparison chart
# Completers
econ_completers_gems_melted = econ_completers_gems_agg.melt(
    id_vars=['dt', 'set_completed', 'unique_users'], 
    value_vars=['avg_inflows', 'avg_outflows'],
    var_name='flow_type',
    value_name='amount'
)

fig = px.line(econ_completers_gems_melted, 
              x='dt', 
              y='amount',
              color='flow_type',
              facet_row='set_completed',
              title='Gems average inflows and outflows by day - Completers',
              width=1200,
              height=1200,
              hover_data={'amount': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)
fig.show()

# Non-completers
econ_noncompleters_gems_melted = econ_noncompleters_gems_agg.melt(
    id_vars=['dt', 'set_completed', 'unique_users'], 
    value_vars=['avg_inflows', 'avg_outflows'],
    var_name='flow_type',
    value_name='amount'
)

fig = px.line(econ_noncompleters_gems_melted, 
              x='dt', 
              y='amount',
              color='flow_type',
              facet_row='set_completed',
              title='Gems average inflows and outflows by day - Non-Completers',
              width=1200,
              height=1200,
              hover_data={'amount': True, 'unique_users': True})

fig = add_vlines_to_figure(fig, vlines_events)
fig.show()

<!-- hide --> 
## Suggested additional analysis

The following analyses would help answer questions not yet fully covered in the notebook.

### 1. Product category breakdown for completers
The IAP revenue share of completers is clear (15.4%), but we don't know *what* they're buying. Adding a product category dimension to the IAP revenue query (e.g. gems, energy bundles, sticker packs, passes) would reveal whether completers are buying to complete sets or spending on other things — key for understanding their monetisation driver.

### 2. Prestige cadence — when do users prestige relative to event start?
The tier-by-day chart shows the distribution of tiers over time, but doesn't show *when* users first crossed into prestige. A survival curve of time-to-prestige (days since event start) would reveal whether prestige is being hit early (driven by whales) or late (driven by casual grinders who get there by the end).

### 3. Repeat prestige behaviour across events (ThroughTheAges)
ThroughTheAges is the second event with prestige. Compare the prestige rate and speed in ThroughTheAges vs. Diorama — do users who prestiged in Diorama prestige again faster? This would show whether prestige creates habitual behaviour and informs whether it is re-engaging the same cohort or acquiring new ones.

### 4. Hangover duration — when does completer activity normalise?
The hangover section tracks return rate and revenue, but doesn't surface a clear answer to "how many days after an event does the completer bump last?" Fitting a decay curve to post-event ARPDAU or plotting the delta between completers and non-completers by days-after-event would give an answer.

In [ ]:
export_notebook_html(
# Exports the notebook to HTML for sharing and archival
    notebook_path='./prestige.ipynb',
    output_path='./prestige.html',
)

Saved to prestige.html

PosixPath('prestige.html')